"use client";
import { FormEvent, useEffect, useState } from "react";
import { PageShell } from "@/components/PageShell";
import { api } from "@/lib/api";
import { getSessionToken } from "@/lib/session";
const refOf=(x:any)=>String(x?.reference||x?.order?.reference||x?.data?.reference||"");
export default function TempMail(){
 const[search,setSearch]=useState("");const[services,setServices]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[price,setPrice]=useState<any>(null);const[order,setOrder]=useState<any>(null);const[message,setMessage]=useState("Loading services…");const[busy,setBusy]=useState(false);
 async function load(q=""){try{const data:any=await api.tempMail.services(q);const list=Array.isArray(data)?data:(data?.services||data?.items||data?.data||[]);setServices(Array.isArray(list)?list:[]);setMessage(Array.isArray(list)&&list.length?"":"No services found.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to load services")}}
 useEffect(()=>{load()},[]);
 async function choose(item:any){setSelected(item);setPrice(null);const code=String(item.service_code||item.code||item.id||"");if(!code)return;try{setPrice(await api.tempMail.price(code))}catch(e){setMessage(e instanceof Error?e.message:"Unable to load price")}}
 async function buy(e:FormEvent){e.preventDefault();const token=getSessionToken();if(!token)return setMessage("Please sign in first.");if(!selected)return setMessage("Choose a service first.");const service_code=String(selected.service_code||selected.code||selected.id||"");setBusy(true);setMessage("Creating temporary inbox…");try{const result:any=await api.tempMail.order(token,{service_code});setOrder(result?.order||result?.data||result);setMessage("Temporary inbox created.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to create inbox")}finally{setBusy(false)}}
 async function refresh(){const token=getSessionToken(),reference=refOf(order);if(!token||!reference)return;setBusy(true);try{const result:any=await api.tempMail.status(token,reference);setOrder(result?.order||result?.data||result);setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"Unable to refresh inbox")}finally{setBusy(false)}}
 async function cancel(){const token=getSessionToken(),reference=refOf(order);if(!token||!reference)return;setBusy(true);try{await api.tempMail.cancel(token,reference);setMessage("Temporary inbox cancelled.");await refresh()}catch(e){setMessage(e instanceof Error?e.message:"Unable to cancel inbox")}finally{setBusy(false)}}
 const reference=refOf(order);const email=order?.email||order?.address||order?.email_address||"";const status=order?.status||"Active";const raw=order?.messages||order?.emails||order?.inbox||[];const mails=Array.isArray(raw)?raw:raw?[raw]:[];const otp=order?.otp||order?.code||order?.verification_code||order?.data?.otp||"";const ended=/cancel|expired|complete|refunded/i.test(String(status));const priceNgn=price?.price_ngn??price?.final_price_ngn??price?.data?.price_ngn??price?.data?.final_price_ngn??null;
 return <PageShell title="Temp Mail" subtitle="Temporary email for verification">{!order?<><form className="panel" onSubmit={(e)=>{e.preventDefault();load(search)}}><div className="field"><label>Search services</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Microsoft, Google…" /></div><button className="secondaryButton" type="submit">Search</button></form><div className="list">{services.map((item:any,i)=><button type="button" className="listItem" key={item.service_code||item.code||item.id||i} onClick={()=>choose(item)}><div><b>{item.name||item.service_name||item.title||"Email service"}</b><br/><small>{item.description||"Temporary inbox"}</small></div><span>Choose</span></button>)}</div>{selected&&<form className="panel" onSubmit={buy}><h3>{selected.name||selected.service_name||selected.title}</h3><p>{priceNgn!=null?`₦${Number(priceNgn).toLocaleString()}`:"Price confirmed at checkout"}</p><button className="primaryButton" disabled={busy}>{busy?"Creating…":"Buy Temp Mail"}</button></form>}</>:<div className="panel"><p className="eyebrow">{status}</p><h2>{email||"Temporary inbox"}</h2>{reference&&<small>Ref: {reference}</small>}{otp&&<div className="price" style={{marginTop:12}}>OTP: {otp}</div>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:16}}><button className="secondaryButton" disabled={busy} onClick={refresh}>Refresh inbox</button>{!ended&&<button className="secondaryButton" disabled={busy} onClick={cancel}>Cancel</button>}</div><div style={{marginTop:18}}><h3>Inbox</h3>{mails.length?<div className="list">{mails.map((mail:any,i)=><div className="listItem" key={mail.id||i}><div><b>{mail.subject||mail.sender||mail.from||"Message"}</b><br/><span>{mail.code||mail.otp||mail.text||mail.message||mail.body||String(mail)}</span></div></div>)}</div>:<p>No message received yet. Tap Refresh inbox to check again.</p>}</div></div>}{message&&<div className="panel"><p className="statusText">{message}</p></div>}</PageShell>
}