"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {PageShell} from "@/components/PageShell";
import {api} from "@/lib/api";
import {getSessionToken} from "@/lib/session";
import styles from "./wallet.module.css";

const money=(value:any)=>{const n=Number(value);return value!==undefined&&value!==null&&Number.isFinite(n)?`₦${n.toLocaleString()}`:"—"};
const dateLabel=(value:any)=>{if(!value)return"";const date=new Date(value);return Number.isNaN(date.getTime())?"":date.toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})};
type TxState="loading"|"ready"|"error"|"signed-out";

export default function Wallet(){
  const[balance,setBalance]=useState("—");const[transactions,setTransactions]=useState<any[]>([]);const[txState,setTxState]=useState<TxState>("loading");const[message,setMessage]=useState("Loading wallet…");const[hidden,setHidden]=useState(false);
  useEffect(()=>{let cancelled=false;async function load(){const token=getSessionToken();if(!token){setBalance("—");setTransactions([]);setTxState("signed-out");setMessage("Please sign in to view your wallet.");return}setTxState("loading");setMessage("Loading wallet…");const[walletResult,txResult]=await Promise.allSettled([api.wallet.get(token),api.wallet.transactions(token)]);if(cancelled)return;if(walletResult.status==="fulfilled"){const wallet:any=walletResult.value;const raw=wallet?.balance_ngn??wallet?.wallet_balance_ngn??wallet?.balance??wallet?.wallet?.balance_ngn??wallet?.data?.balance_ngn??wallet?.data?.balance;setBalance(money(raw))}else setBalance("—");if(txResult.status==="fulfilled"){const tx:any=txResult.value;const list=Array.isArray(tx)?tx:(tx?.transactions||tx?.items||tx?.data||[]);setTransactions(Array.isArray(list)?list:[]);setTxState("ready")}else{setTransactions([]);setTxState("error")}if(walletResult.status==="rejected"&&txResult.status==="rejected")setMessage(walletResult.reason instanceof Error?walletResult.reason.message:"Unable to load wallet");else if(walletResult.status==="rejected")setMessage("Wallet balance is temporarily unavailable.");else if(txResult.status==="rejected")setMessage("Recent transactions are temporarily unavailable.");else setMessage("")}load();return()=>{cancelled=true}},[]);
  const emptyTitle=txState==="loading"?"Loading transactions…":txState==="error"?"Transactions unavailable":txState==="signed-out"?"Sign in to view activity":"No transactions yet";
  const emptyCopy=txState==="loading"?"Fetching your latest wallet activity.":txState==="error"?"We couldn’t load your recent wallet activity right now.":txState==="signed-out"?"Your wallet activity will appear here after you sign in.":"Your wallet activity will appear here.";
  const recent=transactions.slice(0,5);
  return <PageShell title="" subtitle=""><div className={styles.screen}><header className={styles.header}><h1>Wallet</h1><p>Manage your balance and transactions.</p></header><section className={styles.balanceCard}><div className={styles.balanceTop}><span>Total Balance</span><button className={styles.toggle} type="button" aria-pressed={hidden} onClick={()=>setHidden(v=>!v)}>◉ {hidden?"Show":"Show / Hide"}</button></div><div className={styles.balance}>{hidden?"••••••":balance}</div><p className={styles.currency}>Preferred Currency&nbsp; • &nbsp;NGN</p><Link className={styles.addFunds} href="/add-funds">Add Funds</Link></section><h2 className={styles.sectionTitle}>Quick Actions</h2><section className={styles.quickGrid}><Link className={styles.quickCard} href="/wallet/transactions"><span>≡</span><b>Transaction History</b></Link><Link className={styles.quickCard} href="/currency-balance"><span>$</span><b>Currency</b></Link><Link className={styles.quickCard} href="/add-funds"><span>▣</span><b>Payment Methods</b></Link><Link className={styles.quickCard} href="/profile"><span>↗</span><b>Refer &amp; Earn</b></Link></section><div className={styles.transactionsHeader}><h2>Recent Transactions</h2><Link href="/wallet/transactions">View all&nbsp; ›</Link></div><section className={styles.transactions} aria-busy={txState==="loading"}>{recent.length?recent.map((tx:any,i)=>{const amount=tx.amount_ngn??tx.final_amount_ngn??tx.amount;const n=Number(amount);const type=tx.type||tx.kind||tx.category||tx.description||"Transaction";const status=tx.status||"Wallet activity";const date=dateLabel(tx.created_at||tx.date||tx.timestamp);return <div className={styles.txRow} key={tx.id||tx.reference||i}><div><div className={styles.txTitle}>{type}</div><div className={styles.txMeta}>{date||status}</div></div><div><div className={styles.txAmount}>{Number.isFinite(n)&&n>0?"+":""}{money(amount)}</div><div className={styles.txStatus}>{status}</div></div></div>}):<div className={styles.empty}><b>{emptyTitle}</b><p>{emptyCopy}</p></div>}</section>{message&&(transactions.length>0||txState==="error")&&<p className={styles.message} role="status">{message}</p>}</div></PageShell>
}
