"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {wickspendApi} from "@/lib/api";
import {getSessionToken} from "@/lib/session";
import styles from "./delivery.module.css";

const money=(v:any)=>`₦${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;

export default function DeliveryPage(){
 const[order,setOrder]=useState<any|null>(null),[message,setMessage]=useState("Loading your delivery…");
 useEffect(()=>{let cancelled=false;(async()=>{try{const reference=new URLSearchParams(window.location.search).get("reference")||"";const token=getSessionToken();if(!token)throw new Error("Please sign in to view this delivery.");if(!reference)throw new Error("Order reference is missing.");const d:any=await wickspendApi(`wickspend/backend/marketplace/manual-order?reference=${encodeURIComponent(reference)}`,{token});if(cancelled)return;if(!d?.ok)throw new Error(d?.code||"Delivery unavailable.");setOrder(d.order);setMessage("")}catch(e){if(!cancelled)setMessage(e instanceof Error?e.message:"Delivery unavailable.")}})();return()=>{cancelled=true}},[]);
 function copy(value:string){navigator.clipboard?.writeText(value)}
 const delivery=order?.delivery||{};const text=typeof delivery?.text==="string"?delivery.text:"";const url=typeof delivery?.url==="string"?delivery.url:"";const dataUrl=typeof delivery?.data_url==="string"?delivery.data_url:"";const filename=String(delivery?.filename||"wickspend-download");
 return <main className={styles.page}><div className={styles.shell}><Link className={styles.back} href="/orders">‹</Link><header className={styles.header}><h1>Order Delivery</h1><p>Protected digital delivery for your WickSpend purchase.</p></header>{message?<div className={message.toLowerCase().includes("loading")?styles.pending:styles.error}>{message}</div>:order&&<><section className={`${styles.card} ${styles.meta}`}><div className={styles.row}><span>Product</span><strong>{order.product_name||"Marketplace Product"}</strong></div><div className={styles.row}><span>Order</span><strong>{order.reference}</strong></div><div className={styles.row}><span>Price</span><strong>{money(order.amount_ngn)}</strong></div><div className={styles.row}><span>Status</span><strong>{String(order.status||"").replaceAll("_"," ")}</strong></div></section><section className={`${styles.card} ${styles.delivery}`}><h2>{order.delivery_available?"Your delivery":"Delivery pending"}</h2>{!order.delivery_available?<p className={styles.notice}>This order has not been delivered yet. Once fulfillment is completed, the delivery will become available here.</p>:<>{text&&<><div className={styles.pre}>{text}</div><div className={styles.actions}><button className={styles.secondary} onClick={()=>copy(text)}>Copy Delivery</button></div></>}{url&&<div className={styles.actions}><a className={styles.button} href={url} target="_blank" rel="noreferrer">Open Delivery</a><button className={styles.secondary} onClick={()=>copy(url)}>Copy Link</button></div>}{dataUrl&&<div className={styles.actions}><a className={styles.button} href={dataUrl} download={filename}>Download {filename}</a></div>}{!text&&!url&&!dataUrl&&<p className={styles.notice}>Your delivery is confirmed. Open this order again if the delivery content is still being prepared.</p>}</>}</section><section className={styles.card}><p className={styles.notice}>This delivery is returned only after WickSpend validates your signed-in session and verifies that this order belongs to you. Do not share credentials or download contents publicly.</p></section></>}</div></main>
}
