"use client";

import {FormEvent,useEffect,useRef,useState} from "react";
import {PageShell} from "@/components/PageShell";
import {api} from "@/lib/api";
import {getSessionToken} from "@/lib/session";
import styles from "./add-funds.module.css";

const presets=[500,1000,2000,5000,10000];
const money=(value:any)=>{const n=Number(value);return value!==undefined&&value!==null&&Number.isFinite(n)?`₦${n.toLocaleString()}`:"—"};
function paymentUrl(payload:any){const raw=payload?.checkout_url||payload?.payment_url||payload?.authorization_url||payload?.data?.checkout_url||payload?.data?.payment_url||payload?.data?.authorization_url;if(!raw)return"";try{const url=new URL(String(raw),window.location.origin);return url.protocol==="https:"||url.protocol==="http:"?url.toString():""}catch{return""}}

export default function AddFunds(){
  const[amount,setAmount]=useState("2000"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[balance,setBalance]=useState("—"),requestSeq=useRef(0);
  useEffect(()=>{let cancelled=false;const token=getSessionToken();if(token)api.wallet.get(token).then((wallet:any)=>{if(cancelled)return;const raw=wallet?.balance_ngn??wallet?.wallet_balance_ngn??wallet?.balance??wallet?.wallet?.balance_ngn??wallet?.data?.balance_ngn??wallet?.data?.balance;setBalance(money(raw))}).catch(()=>{if(!cancelled)setBalance("—")});return()=>{cancelled=true}},[]);
  const value=Number(amount),valid=Number.isFinite(value)&&Number.isInteger(value)&&value>=500;
  async function submit(e:FormEvent){e.preventDefault();if(busy)return;const token=getSessionToken();if(!token){setMessage("Please sign in first.");return}if(!valid){setMessage("Enter a whole amount of at least ₦500.");return}const seq=++requestSeq.current;setBusy(true);setMessage("Creating secure payment…");try{const r:any=await api.wallet.initializeFunding(token,value);if(seq!==requestSeq.current)return;const url=paymentUrl(r);if(!url)throw new Error("A valid payment link was not returned by the funding service.");setMessage("Redirecting to secure payment…");window.location.assign(url)}catch(err){if(seq===requestSeq.current)setMessage(err instanceof Error?err.message:"Unable to initialize funding")}finally{if(seq===requestSeq.current)setBusy(false)}}
  return <PageShell title="" subtitle=""><div className={styles.screen}><header className={styles.header}><h1>Wallet</h1><p>Manage your balance and transactions.</p></header><section className={styles.balanceCard}><div className={styles.balanceTop}><span>Total Balance</span><span>◉ Show / Hide</span></div><div className={styles.balance}>{balance}</div><p className={styles.currency}>Preferred Currency&nbsp; • &nbsp;NGN</p><div className={styles.addChip}>Add Funds</div></section><h2 className={styles.title}>Add Funds</h2><form onSubmit={submit} aria-busy={busy}><div className={styles.current}><span>Current Balance</span><strong>{balance}</strong></div><label className={styles.label} htmlFor="fundingAmount">Enter Amount</label><div className={styles.amountBox}><span>₦</span><input id="fundingAmount" aria-label="Amount in NGN" type="number" min="500" step="1" inputMode="numeric" value={amount} disabled={busy} onChange={e=>{requestSeq.current++;setAmount(e.target.value);setMessage("")}}/></div><div className={styles.presets}>{presets.map(v=><button type="button" key={v} className={Number(amount)===v?styles.active:""} aria-pressed={Number(amount)===v} disabled={busy} onClick={()=>{requestSeq.current++;setAmount(String(v));setMessage("")}}>₦{v>=1000?`${v/1000}k`:v}</button>)}</div><label className={styles.label}>Payment Method</label><div className={styles.method}><span>Card / Bank Transfer</span><span>⌄</span></div><p className={styles.minimum}>Minimum funding: ₦500.</p><button className={styles.cta} type="submit" disabled={busy||!valid}>{busy?"Preparing payment…":"Continue"}</button>{message&&<p className={styles.message} role="status">{message}</p>}</form></div></PageShell>
}
