"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {BottomNav} from "@/components/BottomNav";
import {api} from "@/lib/api";
import {getSessionToken} from "@/lib/session";
import s from "./boostly.module.css";

const platforms=[['IG','Instagram'],['TT','TikTok'],['FB','Facebook'],['YT','YouTube'],['X','X (Twitter)'],['TG','Telegram'],['P','Pinterest'],['＋','Other']] as const;
const serviceId=(x:any)=>String(x?.service_id||x?.id||x?.code||'');
const nameOf=(x:any)=>String(x?.name||x?.title||x?.service_name||'Boostly service');
const platformOf=(x:any)=>String(x?.platform||x?.category||x?.name||'Other');
const price=(x:any)=>{const raw=x?.price_usd??x?.final_price_usd??x?.rate_usd??x?.price??x?.rate??null,n=Number(raw);return raw!=null&&Number.isFinite(n)?n:null};
const money=(x:any)=>price(x)==null?'View':`$${price(x)!.toFixed(2)} / 1K`;
const refill=(x:any)=>x?.refill_days?`Refill ${x.refill_days} days`:x?.refill===true?'Refill available':x?.refill===false?'No refill':String(x?.refill||'Service details');

export default function Boostly(){
 const router=useRouter(); const[view,setView]=useState<'home'|'list'|'detail'|'order'|'confirm'|'success'>('home'); const[services,setServices]=useState<any[]>([]); const[selected,setSelected]=useState<any>(null); const[platform,setPlatform]=useState('Instagram'); const[search,setSearch]=useState(''); const[link,setLink]=useState(''); const[quantity,setQuantity]=useState(1000); const[message,setMessage]=useState(''); const[busy,setBusy]=useState(false); const[order,setOrder]=useState<any>(null); const mounted=useRef(true);
 useEffect(()=>()=>{mounted.current=false},[]);
 async function load(q='',p=platform){setBusy(true);setMessage('Loading services…');try{const query=[p==='Other'?'':p,q].filter(Boolean).join(' ');const d:any=await api.boostly.services(query?{search:query}:{page:1,limit:50});if(!mounted.current)return;const list=Array.isArray(d)?d:(d?.services||d?.items||d?.data||[]);const safe=Array.isArray(list)?list.filter((x:any)=>serviceId(x)):[];setServices(safe);setMessage(safe.length?'':'No services found.')}catch(e){if(mounted.current){setServices([]);setMessage(e instanceof Error?e.message:'Unable to load services')}}finally{if(mounted.current)setBusy(false)}}
 async function openPlatform(p:string){setPlatform(p);setSearch('');setView('list');await load('',p)}
 async function choose(item:any){if(busy)return;setBusy(true);setMessage('Loading service…');try{const d:any=await api.boostly.service(serviceId(item));if(!mounted.current)return;const x=d?.service||d?.data||d||item;setSelected(x);const min=Number(x?.min);setQuantity(Number.isFinite(min)&&min>1000?min:1000);setView('detail');setMessage('')}catch(e){if(mounted.current)setMessage(e instanceof Error?e.message:'Unable to load service')}finally{if(mounted.current)setBusy(false)}}
 function total(){const r=price(selected);return r==null?null:r*(quantity/1000)}
 async function submit(e:FormEvent){e.preventDefault();const t=getSessionToken();if(!t)return setMessage('Please sign in first.');if(!selected)return;const min=Number(selected.min||1),max=Number(selected.max||100000000);if(!link.trim())return setMessage('Enter the target link or username.');if(quantity<min||quantity>max)return setMessage(`Quantity must be between ${min.toLocaleString()} and ${max.toLocaleString()}.`);setBusy(true);setMessage('Placing order…');try{const d:any=await api.boostly.order(t,{service_id:serviceId(selected),link:link.trim(),quantity});if(!mounted.current)return;setOrder(d?.order||d?.data||d);setView('success');setMessage('')}catch(e){if(mounted.current)setMessage(e instanceof Error?e.message:'Unable to place order')}finally{if(mounted.current)setBusy(false)}}
 const back=()=>{if(view==='home')router.back();else if(view==='list')setView('home');else if(view==='detail')setView('list');else if(view==='order')setView('detail');else if(view==='confirm')setView('order')};
 const header=(title:string,sub:string,orders=false)=><div className={`${s.header} ${view==='list'?s.listHeader:''}`}><button className={s.back} onClick={back}>‹</button><div className={s.headCopy}><div className={s.title}>{title}</div><div className={s.subtitle}>{sub}</div></div>{orders&&<button className={s.orders} onClick={()=>router.push('/orders')}>Orders</button>}</div>;
 return <main className={s.page}>
 {view==='home'&&<>{header('Boostly','Social growth services',true)}<form className={s.search} onSubmit={e=>{e.preventDefault();setPlatform('Other');setView('list');load(search,'Other')}}><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search followers, likes, views…"/></form><section className={s.hero}><small>FAST • TRACKED • AFFORDABLE</small><h2>Grow your audience</h2><p>Choose a platform and find the right service.</p></section><h2 className={s.sectionTitle}>Choose a platform</h2><div className={s.platforms}>{platforms.map(([mark,p])=><button className={s.platform} key={p} onClick={()=>openPlatform(p)}><span className={s.mark}>{mark}</span>{p}</button>)}</div><div className={s.popularHead}><h2>Popular services</h2><button onClick={()=>openPlatform('Other')}>View all ›</button></div><div className={s.popular}><button onClick={()=>openPlatform('Instagram')}><span>Instagram followers</span><span>From $0.80</span></button><button onClick={()=>openPlatform('TikTok')}><span>TikTok views</span><span>From $0.35</span></button></div></>}
 {view==='list'&&<>{header(`${platform} Services`,'Live services and final prices')}<form className={`${s.search} ${s.listSearch}`} onSubmit={e=>{e.preventDefault();load(search)}}><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${platform} services`}/></form><div className={s.filters}>{['Followers','Likes','Views','Reels'].map((f,i)=><button key={f} className={`${s.filter}${i===0?' '+s.active:''}`} onClick={()=>{setSearch(f);load(f)}}>{f}</button>)}</div><div className={s.countRow}><span>{services.length} services</span><span>Recommended⌄</span></div><div className={s.serviceList}>{services.map(x=><button className={s.serviceCard} key={serviceId(x)} onClick={()=>choose(x)}><span className={s.serviceTop}><b>{nameOf(x)}</b><strong>{money(x)}</strong></span><span className={s.serviceMeta}>Min {Number(x.min||0).toLocaleString()} • Max {Number(x.max||0).toLocaleString()}</span><span className={s.serviceMeta}>{x.start_time||x.average_time||'Live provider timing'}</span><span className={s.badge}>{refill(x)}</span><span className={s.arrow}>›</span></button>)}{!busy&&!services.length&&<div className={s.empty}>{message||'No services found.'}</div>}</div></>}
 {view==='detail'&&selected&&<>{header('Service Details','Review before ordering')}<section className={s.detailHero}><div className={s.detailIdentity}><span className={s.mark}>{platform.slice(0,2).toUpperCase()}</span><div><b>{nameOf(selected)}</b><small>#{serviceId(selected)}</small></div></div><div className={s.rateRow}><div><small>Rate per 1,000</small><strong>{price(selected)==null?'—':`$${price(selected)!.toFixed(2)}`}</strong></div><span className={s.recommend}>Recommended</span></div></section><section className={s.stats}><div><small>Minimum</small><b>{Number(selected.min||0).toLocaleString()}</b></div><div><small>Maximum</small><b>{Number(selected.max||0).toLocaleString()}</b></div><div><small>Start time</small><b>{selected.start_time||selected.average_time||'Live'}</b></div><div><small>Refill</small><b>{refill(selected).replace('Refill ','')}</b></div></section><section className={s.about}><h2>About this service</h2><div className={s.description}>{selected.description||'Social growth service with provider-tracked delivery. Keep your target account active while the order runs.'}<small>Results and timing may vary by platform activity.</small></div></section><div className={s.note}><span>◇</span> Non-refundable after delivery begins.</div><button className={s.cta} onClick={()=>setView('order')}>Order this service</button></>}
 {view==='order'&&selected&&<>{header('Create Order',nameOf(selected))}<section className={s.orderHero}><span className={s.mark}>{platform.slice(0,2).toUpperCase()}</span><div><b>{nameOf(selected)}</b><small>{money(selected)}</small></div><em>{refill(selected)}</em></section><label className={s.field}><span className={s.fieldHead}><span>{platform} profile link</span><small>{link.trim()?'✓ Link entered':''}</small></span><input className={s.input} value={link} onChange={e=>setLink(e.target.value)} placeholder="Enter target link or username"/></label><div className={s.field}><span className={s.fieldHead}><span>Quantity</span><small>Min {Number(selected.min||0).toLocaleString()} • Max {Number(selected.max||0).toLocaleString()}</small></span><div className={s.quantity}><button onClick={()=>setQuantity(q=>Math.max(Number(selected.min||1),q-100))}>−</button><b>{quantity.toLocaleString()}</b><button onClick={()=>setQuantity(q=>Math.min(Number(selected.max||100000000),q+100))}>＋</button></div><div className={s.presets}>{[100,500,1000,5000,10000].map(q=><button key={q} className={quantity===q?s.active:''} onClick={()=>setQuantity(q)}>{q>=1000?`${q/1000}K`:q}</button>)}</div></div><section className={s.summary}><h2>Order summary</h2><div className={s.summaryRow}><span>Quantity</span><b>{quantity.toLocaleString()}</b></div><div className={s.summaryRow}><span>Rate</span><b>{money(selected)}</b></div><div className={`${s.summaryRow} ${s.total}`}><span>Total</span><b>{total()==null?'At checkout':`$${total()!.toFixed(2)}`}</b></div></section><div className={`${s.note} ${s.status}`}>◷ <span>Estimated start: {selected.start_time||selected.average_time||'provider timing'}</span></div><button className={s.cta} onClick={()=>{if(!link.trim())setMessage('Enter the target link or username.');else setView('confirm')}}>Review order {total()!=null?` • $${total()!.toFixed(2)}`:''}</button></>}
 {view==='confirm'&&selected&&<form onSubmit={submit}>{header('Confirm Order','Review everything before paying')}<section className={s.confirmHero}><small>{platform.toUpperCase()}</small><h2>{nameOf(selected)}</h2><p>{link}</p><div className={s.confirmBottom}><b>{quantity.toLocaleString()} followers</b><strong>{total()==null?'—':`$${total()!.toFixed(2)}`}</strong></div></section><section className={s.detailsBox}><div className={s.summaryRow}><span>Service ID</span><b>#{serviceId(selected)}</b></div><div className={s.summaryRow}><span>Quantity</span><b>{quantity.toLocaleString()}</b></div><div className={s.summaryRow}><span>Rate</span><b>{money(selected)}</b></div><div className={s.summaryRow}><span>Estimated start</span><b>{selected.start_time||selected.average_time||'Live'}</b></div><div className={s.summaryRow}><span>Refill</span><b>{refill(selected)}</b></div></section><section className={s.walletBox}><h3>WickSpend Wallet</h3><div className={s.summaryRow}><span>Payment source</span><b>Wallet balance</b></div><div className={s.summaryRow}><span>Total</span><b>{total()==null?'Confirmed at checkout':`$${total()!.toFixed(2)}`}</b></div></section><div className={`${s.note} ${s.warning}`}>◇ <span>Do not change your username while delivery runs.<br/><small>Orders cannot be edited after submission.</small></span></div><button className={s.cta} disabled={busy}>{busy?'Processing…':`Confirm & Pay${total()!=null?` • $${total()!.toFixed(2)}`:''}`}</button></form>}
 {view==='success'&&<section className={s.success}><div className={s.successMark}>✓</div><h2>Order placed</h2><p>Your Boostly order has been submitted.</p><code>{order?.reference||order?.order_reference||order?.id||'Created'}</code><button onClick={()=>{setOrder(null);setSelected(null);setView('home')}}>Browse more services</button></section>}
 {message&&view!=='list'&&<p className={s.screenMessage} role="status">{message}</p>}<BottomNav/></main>
}