"use client";
import { FormEvent, useEffect, useState } from "react";
import { PageShell } from "@/components/PageShell";
import { api } from "@/lib/api";
import { getSessionToken } from "@/lib/session";
export default function Boostly(){
 const [services,setServices]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[search,setSearch]=useState(""),[link,setLink]=useState(""),[quantity,setQuantity]=useState(100),[message,setMessage]=useState("Loading services…"),[busy,setBusy]=useState(false),[order,setOrder]=useState<any>(null);
 async function load(q=""){try{const d:any=await api.boostly.services(q?{search:q}:{page:1,limit:50});const list=Array.isArray(d)?d:(d?.services||d?.items||d?.data||[]);setServices(Array.isArray(list)?list:[]);setMessage(list?.length?"":"No services found.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to load services")}}
 useEffect(()=>{load()},[]);
 async function choose(item:any){setBusy(true);try{const id=String(item.service_id||item.id||item.code);const d:any=await api.boostly.service(id);setSelected(d?.service||d?.data||d||item);setQuantity(Number(d?.service?.min||d?.data?.min||d?.min||item.min||100));setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"Unable to load service")}finally{setBusy(false)}}
 async function submit(e:FormEvent){e.preventDefault();const t=getSessionToken();if(!t)return setMessage("Please sign in first.");if(!selected)return;setBusy(true);setMessage("Placing order…");try{const service_id=String(selected.service_id||selected.id||selected.code);const d:any=await api.boostly.order(t,{service_id,link,quantity});setOrder(d?.order||d?.data||d);setMessage("Order placed successfully.")}catch(err){setMessage(err instanceof Error?err.message:"Unable to place order")}finally{setBusy(false)}}
 const priceNgn=(x:any)=>x?.price_ngn??x?.final_price_ngn??x?.rate_ngn??null;
 return <PageShell title="Boostly" subtitle="Social media growth services">
  {!selected&&!order&&<><form className="panel" onSubmit={(e)=>{e.preventDefault();load(search)}}><div className="field"><label>Search services</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Instagram followers, TikTok views…"/></div><button className="secondaryButton">Search</button></form><div className="list">{services.map((s:any,i)=><button type="button" className="listItem" key={s.service_id||s.id||i} onClick={()=>choose(s)} disabled={busy} style={{width:"100%",textAlign:"left"}}><div><b>{s.name||s.title||s.service_name||"Boostly service"}</b><br/><small>{s.category||s.platform||"Social growth"}</small></div><strong>{priceNgn(s)!=null?`₦${Number(priceNgn(s)).toLocaleString()}`:"View"}</strong></button>)}</div></>}
  {selected&&!order&&<form className="panel formGrid" onSubmit={submit}><button type="button" className="secondaryButton" onClick={()=>setSelected(null)}>← Services</button><h2>{selected.name||selected.title||"Service details"}</h2>{selected.description&&<p>{selected.description}</p>}<div className="chips"><span className="chip">Min {selected.min??"—"}</span><span className="chip">Max {selected.max??"—"}</span>{selected.refill!=null&&<span className="chip">Refill {String(selected.refill)}</span>}</div><div className="field"><label>Link / username</label><input required value={link} onChange={e=>setLink(e.target.value)} placeholder="Enter the target link"/></div><div className="field"><label>Quantity</label><input required type="number" min={Number(selected.min||1)} max={Number(selected.max||100000000)} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></div>{priceNgn(selected)!=null?<div className="price">₦{Number(priceNgn(selected)).toLocaleString()}</div>:<p className="statusText">Price confirmed at checkout.</p>}<button className="primaryButton" disabled={busy}>{busy?"Processing…":"Confirm & Pay"}</button></form>}
  {order&&<div className="panel"><p className="eyebrow">{order.status||"Processing"}</p><h2>Boostly order</h2><p>Reference: {order.reference||order.order_reference||order.id||"Created"}</p><p>{order.message||"Your order has been submitted and will appear in Orders."}</p><button className="secondaryButton" onClick={()=>{setOrder(null);setSelected(null)}}>Browse more services</button></div>}
  {message&&<div className="panel"><p className="statusText">{message}</p></div>}
 </PageShell>
}
