import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getPublishedTutorials } from "@/lib/tutorials-server";
import { Tutorial, tutorialDate, tutorialSlug } from "@/lib/tutorials";
import TutorialDetailClient from "./TutorialDetailClient";

async function resolveTutorial(segment:string):Promise<{tutorial:Tutorial;all:Tutorial[]}|null>{const all=await getPublishedTutorials();const tutorial=all.find(t=>String(t.id)===segment||tutorialSlug(t)===segment);return tutorial?{tutorial,all}:null}
const absolute=(value?:string|null)=>!value?undefined:value.startsWith("http")?value:`https://wickspend.com${value.startsWith("/")?"":"/"}${value}`;
function productLink(t:Tutorial){const x=`${t.title} ${t.description||""}`.toLowerCase();if(x.includes("rent"))return["Rent a virtual number","/rent-number"] as const;if(x.includes("number")||x.includes("otp"))return["Buy a virtual number","/buy-number"] as const;if(x.includes("wallet")||x.includes("fund"))return["Fund your WickSpend wallet","/add-funds"] as const;return["Explore WickSpend","/"] as const}

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const result=await resolveTutorial(id);if(!result)return{title:"Tutorial unavailable",robots:{index:false,follow:true}};const {tutorial}=result;return{title:tutorial.title,description:tutorial.description||`Watch ${tutorial.title} on WickSpend.`,alternates:{canonical:`/tutorials/${tutorialSlug(tutorial)}`},openGraph:{title:`${tutorial.title} | WickSpend`,description:tutorial.description||`Watch this WickSpend tutorial.`,url:`/tutorials/${tutorialSlug(tutorial)}`,type:"video.other",images:tutorial.thumbnail_url?[{url:tutorial.thumbnail_url}]:undefined}}}

export default async function TutorialPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const result=await resolveTutorial(id);if(!result)notFound();const {tutorial,all}=result;const slug=tutorialSlug(tutorial);const related=all.filter(t=>String(t.id)!==String(tutorial.id)).slice(0,3);const [cta,href]=productLink(tutorial);const video={"@context":"https://schema.org","@type":"VideoObject",name:tutorial.title,description:tutorial.description||tutorial.title,thumbnailUrl:absolute(tutorial.thumbnail_url),uploadDate:tutorialDate(tutorial)||undefined,contentUrl:absolute(tutorial.video_url),url:`https://wickspend.com/tutorials/${slug}`};return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(video)}}/>
  <TutorialDetailClient tutorial={tutorial}/>
  <section className="seoContent" aria-label="Tutorial guide"><h2>About this tutorial</h2><p>{tutorial.description||"Follow the video above for the published WickSpend walkthrough."}</p><h2>Troubleshooting</h2><p>If the video does not load, refresh the page and try again. For service availability, price or stock, use the relevant live WickSpend service page because tutorial media does not represent live inventory.</p><h2>Related WickSpend action</h2><p><Link href={href}>{cta}</Link></p>{related.length>0&&<><h2>Related tutorials</h2><nav className="seoRelatedLinks">{related.map(item=><Link key={String(item.id)} href={`/tutorials/${tutorialSlug(item)}`}>{item.title}</Link>)}</nav></>}<h2>Tutorial FAQ</h2><details><summary>Does this tutorial show live prices or stock?</summary><p>No. Live service pages remain the source of truth for changing prices, stock and availability.</p></details><details><summary>Where can I find more WickSpend guides?</summary><p><Link href="/tutorials">Browse all published tutorials</Link>.</p></details></section>
</>}
