"use client";

import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {BottomNav} from "@/components/BottomNav";
import {api,ApiError} from "@/lib/api";
import {getSessionToken} from "@/lib/session";
import styles from "./refer-earn.module.css";

type ReferralItem={id?:string|number;name?:string;masked_identifier?:string;status?:string;date?:string;created_at?:string;reward_amount_ngn?:number;reward_ngn?:number};
type ReferralData={referral_code?:string;referral_link?:string;total_referral_signups?:number;funded_referrals?:number;successful_referrals?:number;pending_referrals?:number;total_rewards_paid?:number;rewards_paid_today?:number;rewards_paid_this_month?:number;available_rewards?:number;referral_history?:ReferralItem[]};

const rules=["The referred person must be a new WickSpend user.","They must register through your referral link.","They must meet WickSpend’s required wallet-funding amount.","They must complete the required qualifying purchase.","Rewards can only be earned once per eligible referred user.","Self-referrals are not allowed.","Suspicious or fraudulent referrals are not eligible."];

function Icon({name,size=20}:{name:string;size?:number}){const c={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(name==="back")return <svg {...c}><path d="m15 18-6-6 6-6"/></svg>;if(name==="gift")return <svg {...c}><path d="M20 12v8H4v-8M2 8h20v4H2zM12 8v12"/><path d="M12 8H8.5A2.5 2.5 0 1 1 11 5.5L12 8ZM12 8h3.5A2.5 2.5 0 1 0 13 5.5L12 8Z"/></svg>;if(name==="copy")return <svg {...c}><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M15 9V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h3"/></svg>;if(name==="share")return <svg {...c}><path d="M12 16V4M8 8l4-4 4 4"/><path d="M5 12v7h14v-7"/></svg>;if(name==="users")return <svg {...c}><circle cx="9" cy="8" r="3"/><path d="M3.5 19c.7-3.7 2.5-5.5 5.5-5.5s4.8 1.8 5.5 5.5M16 5.5a3 3 0 0 1 0 5.8M16.5 14c2.2.4 3.5 2 4 5"/></svg>;if(name==="wallet")return <svg {...c}><path d="M4 7h14a2 2 0 0 1 2 2v9H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h11v3"/><path d="M15 11h5v4h-5a2 2 0 0 1 0-4Z"/></svg>;if(name==="check")return <svg {...c}><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></svg>;if(name==="clock")return <svg {...c}><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>;return <svg {...c}><circle cx="12" cy="12" r="9"/></svg>}

const money=(v:unknown)=>{const n=Number(v||0);return `₦${(Number.isFinite(n)?n:0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`};
const number=(v:unknown)=>{const n=Number(v||0);return Number.isFinite(n)?n:0};

export default function ReferEarnPage(){
 const router=useRouter();
 const[data,setData]=useState<ReferralData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[feedback,setFeedback]=useState(""),[open,setOpen]=useState(false);
 useEffect(()=>{let active=true;const token=getSessionToken();if(!token){router.replace("/login");return()=>{active=false}}api.referrals.get(token).then((payload:any)=>{if(!active)return;setData(payload?.data||payload?.referrals||payload||{});setError("")}).catch((e:any)=>{if(!active)return;setError(e instanceof ApiError?e.message:"Couldn’t load your referral dashboard right now.")}).finally(()=>active&&setLoading(false));return()=>{active=false}},[router]);
 const link=useMemo(()=>data?.referral_link||((data?.referral_code&&typeof window!=="undefined")?`${window.location.origin}/ref/${data.referral_code}`:""),[data]);
 const history=Array.isArray(data?.referral_history)?data!.referral_history!:[];
 async function copy(){if(!link)return;try{await navigator.clipboard.writeText(link);setFeedback("Referral link copied");setTimeout(()=>setFeedback(""),1800)}catch{setFeedback("Couldn’t copy the link")}}
 async function share(){if(!link)return;try{if(navigator.share){await navigator.share({title:"Join WickSpend",text:"Join WickSpend with my referral link",url:link})}else{await copy()}}catch(err:any){if(err?.name!=="AbortError")setFeedback("Couldn’t share the link")}}
 return <main className={styles.screen}>
  <header className={styles.header}><button className={styles.back} onClick={()=>router.back()} aria-label="Go back"><Icon name="back"/></button><div className={styles.heading}><h1>Refer & Earn</h1><p>Invite friends and earn rewards</p></div><span/></header>
  {loading?<><div className={`${styles.glass} ${styles.stateCard}`}><div className={styles.skeleton}/></div><section className={styles.section}><div className={styles.stats}>{[1,2,3,4].map(i=><div key={i} className={`${styles.glass} ${styles.stat}`}><div className={styles.skeleton}/></div>)}</div></section></>:<>
   {error&&<div className={`${styles.glass} ${styles.stateCard}`}>{error}</div>}
   <section className={`${styles.glass} ${styles.summary}`}><div className={styles.summaryTop}><div><div className={styles.eyebrow}>Total Rewards</div><div className={styles.total}>{money(data?.total_rewards_paid)}</div></div><div className={styles.iconBox}><Icon name="gift"/></div></div><div className={styles.available}><span>Available Rewards</span><b>{money(data?.available_rewards)}</b></div></section>
   <section className={styles.section}><h2 className={styles.sectionTitle}>Your Referral Link</h2><div className={`${styles.glass} ${styles.linkCard}`}><div className={styles.linkRow}><div className={styles.linkBox}>{link||"Referral link unavailable"}</div><button className={styles.copyBtn} onClick={copy} disabled={!link}><Icon name="copy" size={16}/>Copy Link</button></div><button className={styles.shareBtn} onClick={share} disabled={!link}><Icon name="share" size={16}/>Share Referral Link</button><div className={styles.feedback} aria-live="polite">{feedback}</div></div></section>
   <section className={styles.section}><h2 className={styles.sectionTitle}>Referral Stats</h2><div className={styles.stats}>{[["users","Total Referrals",data?.total_referral_signups],["wallet","Funded Referrals",data?.funded_referrals],["check","Successful Referrals",data?.successful_referrals],["clock","Pending Referrals",data?.pending_referrals]].map(([icon,label,value])=><div className={`${styles.glass} ${styles.stat}`} key={String(label)}><div className={styles.statIcon}><Icon name={String(icon)} size={18}/></div><b>{number(value)}</b><span>{String(label)}</span></div>)}</div></section>
   <section className={styles.section}><h2 className={styles.sectionTitle}>Referral Earnings</h2><div className={`${styles.glass} ${styles.earnings}`}><div className={styles.earningRow}><span>Total Rewards Paid</span><b>{money(data?.total_rewards_paid)}</b></div><div className={styles.earningRow}><span>Rewards Today</span><b>{money(data?.rewards_paid_today)}</b></div><div className={styles.earningRow}><span>Rewards This Month</span><b>{money(data?.rewards_paid_this_month)}</b></div></div></section>
   <section className={styles.section}><h2 className={styles.sectionTitle}>How Refer & Earn Works</h2><div className={`${styles.glass} ${styles.steps}`}>{[["Invite a Friend","Share your unique WickSpend referral link."],["They Join & Fund","Your friend creates their WickSpend account through your link and funds their wallet."],["Earn Your Reward","Receive your referral reward after they complete the qualifying requirements."]].map((s,i)=><div className={styles.step} key={s[0]}><div className={styles.stepNum}>{i+1}</div><div><b>{s[0]}</b><p>{s[1]}</p></div></div>)}</div></section>
   <section className={styles.section}><h2 className={styles.sectionTitle}>Recent Referrals</h2><div className={`${styles.glass} ${styles.activity}`}>{history.length?history.map((r,i)=><div className={styles.activityRow} key={String(r.id??i)}><div><div className={styles.activityName}>{r.name||r.masked_identifier||"WickSpend user"}</div><div className={styles.activityMeta}>{r.date||r.created_at?new Date(r.date||r.created_at||"").toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):""}</div></div><div className={styles.activityRight}><div className={styles.status}>{r.status||"Pending"}</div><div className={styles.reward}>{number(r.reward_amount_ngn??r.reward_ngn)>0?`+${money(r.reward_amount_ngn??r.reward_ngn)}`:"—"}</div></div></div>):<div className={styles.empty}><div className={styles.emptyIcon}><Icon name="users"/></div><h3>No referrals yet</h3><p>Share your referral link to start earning rewards.</p><button className={styles.primaryBtn} onClick={share} disabled={!link}>Invite Friends</button></div>}</div></section>
   <section className={styles.section}><div className={`${styles.glass} ${styles.accordion}`}><button className={styles.accordionBtn} onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span>Referral Rules</span><span>{open?"−":"+"}</span></button>{open&&<ul className={styles.rules}>{rules.map(rule=><li key={rule}>{rule}</li>)}</ul>}</div></section>
  </>}
  <BottomNav/>
 </main>
}