"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { wickspendApi } from "@/lib/api";
import { getSessionToken } from "@/lib/session";
import styles from "../resellers/resellers.module.css";

const money=(value:unknown)=>`₦${Number(value||0).toLocaleString("en-NG",{maximumFractionDigits:2})}`;
const date=(value:unknown)=>value?new Date(String(value)).toLocaleString():"—";

export default function AdminMiniStoreRentalsPage(){
 const[items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[page,setPage]=useState(1),[meta,setMeta]=useState<any>({});
 const load=useCallback(async()=>{const token=getSessionToken();if(!token){setMessage("Admin session required.");setLoading(false);return}setLoading(true);setMessage("");try{const query=new URLSearchParams({search,status,page:String(page),limit:"50"});const result:any=await wickspendApi(`wickspend/backend/admin/store/rentals?${query}`,{token,preserveSessionOn401:true});setItems(Array.isArray(result.items)?result.items:Array.isArray(result.rentals)?result.rentals:[]);setMeta(result)}catch(error){setMessage(error instanceof Error?error.message:"Unable to load Mini Store rentals.")}finally{setLoading(false)}},[search,status,page]);
 useEffect(()=>{load()},[load]);
 return <main className={styles.page}><div className={styles.shell}><header className={styles.header}><Link className={styles.back} href="/admin/menu">‹</Link><div><span>WickSpend Admin</span><h1>Mini Store Rentals</h1><p>Inspect store, customer, provider, pricing and transaction links.</p></div><button className={styles.refresh} onClick={load} disabled={loading}>{loading?"Loading…":"Refresh"}</button></header>{message&&<div className={styles.error}>{message}</div>}<section className={styles.toolbar}><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder="Search store, customer, rental, number or transaction"/><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="all">All statuses</option><option value="active">Active</option><option value="expired">Expired</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></section><section className={styles.card}>{loading?<div className={styles.empty}>Loading rental records…</div>:items.length?<div className={styles.tableWrap}><table><thead><tr><th>Store / Customer</th><th>Rental / Provider</th><th>Service</th><th>Number</th><th>Provider cost</th><th>Charged</th><th>Reseller revenue</th><th>WickSpend revenue</th><th>Status / Expiry</th><th>Transaction</th></tr></thead><tbody>{items.map((item:any)=><tr key={item.reference||item.rental_id}><td><b>{item.store_name||item.store_slug||item.reseller_id}</b><small>{item.customer_name||item.customer_email||item.customer_id}</small></td><td><b>{item.reference||item.rental_id}</b><small>{item.provider_order_id||item.gotsms_order_id||"—"}</small></td><td><b>{item.service_name||item.service_code}</b><small>{item.country_name||item.country_code}</small></td><td>{item.phone_number||"—"}</td><td>{money(item.provider_cost_ngn)}</td><td>{money(item.customer_charged_ngn||item.sale_amount_ngn)}</td><td>{money(item.reseller_revenue_ngn||item.reseller_profit_ngn)}</td><td>{money(item.wickspend_revenue_ngn)}</td><td><b>{item.status}</b><small>{date(item.expires_at)}</small></td><td><b>{item.transaction_reference||"—"}</b><small>{date(item.created_at||item.started_at)}</small></td></tr>)}</tbody></table></div>:<div className={styles.empty}>No Mini Store rentals match these filters.</div>}<div className={styles.toolbar}><button className={styles.secondary} disabled={page<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>Previous</button><span className={styles.help}>Page {meta.page||page} · {meta.total||0} rentals</span><button className={styles.secondary} disabled={!meta.has_more} onClick={()=>setPage(value=>value+1)}>Next</button></div></section></div></main>
}
