import { clearSessionToken } from "@/lib/session";
import { clearVerifiedBalance } from "@/lib/client-cache";

const API_BASE = (process.env.NEXT_PUBLIC_WICKSPEND_API_BASE || "https://n8n.wickspend.com/webhook").replace(/\/$/, "");
export type ApiOptions = RequestInit & { token?: string | null };
export class ApiError extends Error { status:number; code?:string; payload?:unknown; constructor(status:number,message:string,code?:string,payload?:unknown){super(message);this.name="ApiError";this.status=status;this.code=code;this.payload=payload;} }
const SAFE_STATUS_MESSAGES:Record<number,string>={400:"We couldn’t complete that request. Please check the details and try again.",401:"Your session has expired. Please sign in again.",402:"Your wallet balance is too low for this purchase.",409:"This request could not be completed because the item or request state changed.",429:"Too many requests. Please try again shortly.",503:"This service is temporarily unavailable. Please try again later."};
function safeMessage(status:number,code?:string){const c=(code||"").toUpperCase();if(c==="INSUFFICIENT_BALANCE")return SAFE_STATUS_MESSAGES[402];if(c==="INVALID_OR_EXPIRED_SESSION"||c==="UNAUTHORIZED")return SAFE_STATUS_MESSAGES[401];if(c==="INVALID_TARGET_LINK")return "Enter a valid target link and try again.";if(c==="INVALID_QUANTITY"||c==="QUANTITY_OUT_OF_RANGE")return "The quantity is outside the allowed range for this service.";if(c==="INVALID_REQUEST_KEY")return "This order request could not be verified. Please try again.";if(c==="SERVICE_NOT_FOUND")return "This service is no longer available. Please choose another service.";if(c==="EMAIL_NOT_FOUND")return "Unable to send a login code right now. Please try again.";if(c==="INVALID_EMAIL_CODE")return "The verification code is incorrect.";if(c==="EMAIL_CODE_EXPIRED_OR_NOT_FOUND"||c==="EMAIL_CODE_EXPIRED"||c==="OTP_EXPIRED")return "This verification code has expired. Request a new one.";if(c==="TOO_MANY_ATTEMPTS"||c==="EMAIL_CODE_ATTEMPTS_EXCEEDED"||c==="OTP_ATTEMPTS_EXCEEDED")return "Too many attempts. Please request a new code.";if(c==="ACCOUNT_LINKING_CONFLICT"||c==="EMAIL_LINK_CONFLICT"||c==="LINK_REQUIRED")return "We couldn't safely sign you in with this email. Please use your existing login method or contact WickSpend support.";if(c==="PROVIDER_STATUS_UNKNOWN")return "Processing — we’re confirming your order.";if(c==="PROVIDER_CANCEL_REJECTED"||c==="NOT_CANCELLABLE"||c==="TEMP_MAIL_NOT_CANCELLABLE")return "This mailbox can no longer be cancelled or refunded.";return SAFE_STATUS_MESSAGES[status]||"We couldn’t complete that request. Please try again."}
export async function wickspendApi<T = unknown>(path:string,options:ApiOptions={}):Promise<T>{const{token,headers,...init}=options;const response=await fetch(`${API_BASE}/${path.replace(/^\//,"")}`,{cache:"no-store",...init,headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{ }),...headers}});const payload=await response.json().catch(()=>null);const pending=response.status===202&&payload&&typeof payload==="object"&&"provider_pending" in payload&&payload.provider_pending===true;if(pending)return payload as T;if(!response.ok||(payload&&typeof payload==="object"&&"ok" in payload&&payload.ok===false)){const code=payload&&typeof payload==="object"&&"code" in payload?String(payload.code):payload&&typeof payload==="object"&&"error" in payload?String(payload.error):undefined;if(response.status===401&&token&&typeof window!=="undefined"){clearSessionToken();if(window.location.pathname!=="/login")window.location.assign("/login")}throw new ApiError(response.status,safeMessage(response.status,code),code,payload)}return payload as T}
export const newRequestKey=(prefix="web")=>`${prefix}-${typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
const query=(params:Record<string,string|number|undefined>={})=>{const q=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!=="")q.set(k,String(v))});return q.toString()};
// Module-level caches survive App Router page changes, keeping visited screens warm.
const publicCache=new Map<string,{expires:number,value:unknown}>();
const publicInflight=new Map<string,Promise<unknown>>();
function publicGet<T=unknown>(path:string,ttlMs=120000):Promise<T>{if(typeof window==="undefined")return wickspendApi<T>(path);const now=Date.now();const cached=publicCache.get(path);if(cached&&cached.expires>now)return Promise.resolve(cached.value as T);const active=publicInflight.get(path);if(active)return active as Promise<T>;const request=wickspendApi<T>(path).then(value=>{publicCache.set(path,{expires:Date.now()+ttlMs,value});return value}).finally(()=>publicInflight.delete(path));publicInflight.set(path,request as Promise<unknown>);return request}
const privateCache=new Map<string,{expires:number,value:unknown}>();
const privateInflight=new Map<string,Promise<unknown>>();
function privateKey(token:string,path:string){let h=2166136261;for(let i=0;i<token.length;i++){h^=token.charCodeAt(i);h=Math.imul(h,16777619)}return `${(h>>>0).toString(36)}:${path}`}
function invalidatePrivate(token:string,paths:string[]){for(const path of paths){const key=privateKey(token,path);privateCache.delete(key);privateInflight.delete(key)}}
function invalidateWalletCache(token:string){invalidatePrivate(token,["wickspend/backend/wallet"]);clearVerifiedBalance(token)}
function walletMutation<T>(token:string,promise:Promise<T>){return promise.then(value=>{invalidateWalletCache(token);invalidatePrivate(token,["wickspend/backend/orders","wickspend/backend/transactions","wickspend/backend/notifications"]);return value})}
function privateGet<T=unknown>(path:string,token:string,ttlMs=15000):Promise<T>{const key=privateKey(token,path);const now=Date.now();const cached=privateCache.get(key);if(cached&&cached.expires>now)return Promise.resolve(cached.value as T);const active=privateInflight.get(key);if(active)return active as Promise<T>;const request=wickspendApi<T>(path,{token}).then(value=>{privateCache.set(key,{expires:Date.now()+ttlMs,value});return value}).finally(()=>privateInflight.delete(key));privateInflight.set(key,request as Promise<unknown>);return request}
export const api={
 auth:{emailStart:(body:unknown)=>wickspendApi("wickspend/backend/auth/email/request",{method:"POST",body:JSON.stringify(body)}),emailVerify:(body:unknown)=>wickspendApi("wickspend/backend/auth/email/verify",{method:"POST",body:JSON.stringify(body)}),telegramStart:(body:unknown)=>wickspendApi("wickspend/backend/auth/telegram/request",{method:"POST",body:JSON.stringify(body)}),telegramVerify:(body:unknown)=>wickspendApi("wickspend/backend/auth/telegram/verify",{method:"POST",body:JSON.stringify(body)}),session:(token:string)=>privateGet("wickspend/backend/auth/session",token,30000),logout:(token:string)=>wickspendApi("wickspend/backend/auth/logout",{method:"POST",token,body:"{}"})},
 wallet:{get:(token:string)=>privateGet("wickspend/backend/wallet",token,10000),transactions:(token:string)=>privateGet("wickspend/backend/transactions",token,20000),initializeFunding:(token:string,amount_ngn:number)=>wickspendApi("wickspend/backend/funding/initialize",{method:"POST",token,body:JSON.stringify({amount_ngn})}),invalidate:(token:string)=>invalidateWalletCache(token)},
 numbers:{catalog:(params:Record<string,string|number|undefined>={})=>{const q=query(params);return publicGet(`wickspend/backend/numbers/catalog${q?`?${q}`:""}`,120000)},countries:(_token?:string)=>publicGet("wickspend/backend/numbers/catalog",120000),services:(_token:string,country_code:string)=>publicGet(`wickspend/backend/numbers/catalog?country_code=${encodeURIComponent(country_code)}`,120000),prices:(_token:string,country_code:string,service_code:string,fresh=false)=>{const path=`wickspend/backend/numbers/catalog?country_code=${encodeURIComponent(country_code)}&service_code=${encodeURIComponent(service_code)}`;if(!fresh)return publicGet(path,120000);publicCache.delete(path);return wickspendApi(path).then(value=>{publicCache.set(path,{expires:Date.now()+120000,value});return value})},buy:(token:string,body:{country_code:string;service_code:string;provider_id?:string;request_key?:string})=>walletMutation(token,wickspendApi("wickspend/backend/numbers/buy",{method:"POST",token,body:JSON.stringify({...body,request_key:body.request_key||newRequestKey("number")})})),premiumCatalog:(token:string)=>wickspendApi("wickspend/backend/numbers/premium-usa/catalog",{token}),premiumBuy:(token:string,input:{service_code:string;request_key?:string})=>walletMutation(token,wickspendApi("wickspend/backend/numbers/premium-usa/buy",{method:"POST",token,body:JSON.stringify({...input,request_key:input.request_key||newRequestKey("premium-usa")})})),active:(token:string)=>wickspendApi("wickspend/backend/numbers/active",{token}),status:(token:string,reference:string)=>wickspendApi(`wickspend/backend/numbers/status?reference=${encodeURIComponent(reference)}`,{token}),cancel:(token:string,reference:string)=>walletMutation(token,wickspendApi("wickspend/backend/numbers/cancel",{method:"POST",token,body:JSON.stringify({reference})}))},
 rentals:{catalog:()=>publicGet("wickspend/backend/rentals/catalog",120000),create:(token:string,input:{service_code:string;duration_minutes:1440|4320|10080|20160|43200;country_code?:"US"|"USA";auto_renew?:boolean;request_key?:string})=>wickspendApi("wickspend/backend/rentals/create",{method:"POST",token,body:JSON.stringify({country_code:input.country_code??"US",service_code:input.service_code,duration_minutes:input.duration_minutes,auto_renew:input.auto_renew===true,request_key:input.request_key??newRequestKey("rent")})}),status:(token:string,reference:string)=>wickspendApi(`wickspend/backend/rentals/status?reference=${encodeURIComponent(reference)}`,{token}),cancel:(token:string,reference:string)=>wickspendApi("wickspend/backend/rentals/cancel",{method:"POST",token,body:JSON.stringify({reference})}),extend:(token:string,reference:string,request_key=newRequestKey("rent-ext"))=>wickspendApi("wickspend/backend/rentals/extend",{method:"POST",token,body:JSON.stringify({reference,request_key})})},
 marketplace:{products:(params:Record<string,string|number|undefined>={})=>{const q=query(params);return publicGet(`wickspend/backend/marketplace/products${q?`?${q}`:""}`,300000)},product:(product_id:string)=>publicGet(`wickspend/backend/marketplace/product?product_id=${encodeURIComponent(product_id)}`,300000),reserve:(token:string,input:{product_id:string;quantity?:number;request_key?:string})=>walletMutation(token,wickspendApi("wickspend/backend/marketplace/reserve",{method:"POST",token,body:JSON.stringify({product_id:input.product_id,quantity:input.quantity??1,request_key:input.request_key||newRequestKey("market")})})),orders:(token:string)=>wickspendApi("wickspend/backend/marketplace/orders",{token})},
 boostly:{services:(params:Record<string,string|number|undefined>={})=>{const q=query(params);return publicGet(`wickspend/backend/boostly/services${q?`?${q}`:""}`,180000)},service:(service_id:string)=>publicGet(`wickspend/backend/boostly/service?service_id=${encodeURIComponent(service_id)}`,180000),order:(token:string,input:Record<string,unknown>)=>{const target_link=String(input.target_link??input.link??"").trim();const body={...input,target_link,request_key:input.request_key||newRequestKey("boostly")};delete (body as Record<string,unknown>).link;return walletMutation(token,wickspendApi<any>("wickspend/backend/boostly/order",{method:"POST",token,body:JSON.stringify(body)}).then(result=>result&&typeof result==="object"&&result.provider_pending===true?{...result,pending_reference:result.reference??null,reference:null,status:"provider_pending"}:result))},orders:(token:string,page=1,limit=20)=>privateGet(`wickspend/backend/boostly/orders?page=${page}&limit=${limit}`,token,15000),orderDetail:(token:string,reference:string)=>wickspendApi(`wickspend/backend/boostly/order?reference=${encodeURIComponent(reference)}`,{token})},
 tempMail:{services:(search="")=>publicGet(`wickspend/backend/temp-mail/services?search=${encodeURIComponent(search)}`,120000),price:(service_code:string)=>publicGet(`wickspend/backend/temp-mail/price?service_code=${encodeURIComponent(service_code)}`,120000),order:(token:string,input:Record<string,unknown>)=>wickspendApi("wickspend/backend/temp-mail/order",{method:"POST",token,body:JSON.stringify({...input,request_key:input.request_key||newRequestKey("mail")})}),status:(token:string,reference:string)=>wickspendApi(`wickspend/backend/temp-mail/order?reference=${encodeURIComponent(reference)}`,{token}),cancel:(token:string,reference:string)=>walletMutation(token,wickspendApi("wickspend/backend/temp-mail/cancel",{method:"POST",token,body:JSON.stringify({reference})})),orders:(token:string,page=1,limit=20)=>wickspendApi(`wickspend/backend/temp-mail/orders?page=${page}&limit=${limit}`,{token})},
 orders:(token:string)=>privateGet("wickspend/backend/orders",token,15000),
 notifications:{list:(token:string)=>privateGet("wickspend/backend/notifications",token,20000),markRead:(token:string,notification_id:string|number)=>wickspendApi("wickspend/backend/notifications/read",{method:"POST",token,body:JSON.stringify({notification_id})}).then(value=>{invalidatePrivate(token,["wickspend/backend/notifications"]);return value}),markAllRead:(token:string)=>wickspendApi("wickspend/backend/notifications/read",{method:"POST",token,body:JSON.stringify({all:true})}).then(value=>{invalidatePrivate(token,["wickspend/backend/notifications"]);return value})},
 support:{chat:(token:string,input:string|Record<string,unknown>)=>wickspendApi("wickspend/backend/support/chat",{method:"POST",token,body:JSON.stringify(typeof input==="string"?{message:input}:input)}),history:(token:string,context?:Record<string,unknown>)=>{const q=context?query(Object.fromEntries(Object.entries(context).filter(([,v])=>typeof v==="string"||typeof v==="number") as [string,string|number][])):"";return wickspendApi(`wickspend/backend/support/history${q?`?${q}`:""}`,{token})},handoff:(token:string,input:Record<string,unknown>)=>wickspendApi("wickspend/backend/support/handoff",{method:"POST",token,body:JSON.stringify(input)})},
 admin:{stats:(token:string)=>wickspendApi("wickspend/backend/admin/stats",{token})}
};
