import { clearSessionTokenIfMatches } from "@/lib/session";
import { clearVerifiedBalance } from "@/lib/client-cache";

const API_BASE = (process.env.NEXT_PUBLIC_WICKSPEND_API_BASE || "https://n8n.wickspend.com/webhook").replace(/\/$/, "");
export type ApiOptions = RequestInit & { token?: string | null; preserveSessionOn401?: boolean; timeoutMs?: number; timeoutMessage?: string };
export class ApiError extends Error { status:number; code?:string; payload?:unknown; constructor(status:number,message:string,code?:string,payload?:unknown){super(message);this.name="ApiError";this.status=status;this.code=code;this.payload=payload;} }
const SAFE_STATUS_MESSAGES:Record<number,string>={400:"We couldn’t complete that request. Please check the details and try again.",401:"Your session has expired. Please sign in again.",402:"Your wallet balance is too low for this purchase.",403:"You do not have permission to access this area.",409:"This request could not be completed because the item or request state changed.",429:"Too many requests. Please try again shortly.",503:"This service is temporarily unavailable. Please try again later."};
function safeMessage(status:number,code?:string){const c=(code||"").toUpperCase();if(c==="INSUFFICIENT_BALANCE")return "Insufficient wallet balance.";if(c==="INVALID_CREDENTIALS")return "Incorrect email or password.";if(c==="INVALID_OR_EXPIRED_SESSION"||c==="UNAUTHORIZED")return status===403?SAFE_STATUS_MESSAGES[403]:"Your session expired. Please sign in again.";if(c==="FORBIDDEN")return SAFE_STATUS_MESSAGES[403];if(c==="INVALID_TARGET_LINK")return "Enter a valid target link and try again.";if(c==="INVALID_QUANTITY"||c==="QUANTITY_OUT_OF_RANGE")return "The quantity is outside the allowed range for this service.";if(c==="INVALID_REQUEST_KEY")return "This order request could not be verified. Please try again.";if(c==="SERVICE_NOT_FOUND")return "This service is currently unavailable.";if(c==="COUNTRY_NOT_SUPPORTED")return "This service is not available in the selected country.";if(c==="INVALID_DURATION")return "This rental duration is no longer available.";if(c==="PRICE_CHANGED")return "The price changed. Review the updated amount and try again.";if(c==="PROVIDER_NO_STOCK")return "No number is currently available. Your wallet has been refunded.";if(c==="PROVIDER_REJECTED")return "The rental provider could not complete this request. Your wallet has been refunded.";if(c==="EMAIL_NOT_FOUND")return "Unable to send a login code right now. Please try again.";if(c==="INVALID_EMAIL")return "Enter a valid email address.";if(c==="RATE_LIMITED")return "Please wait before requesting another code.";if(c==="INVALID_EMAIL_CODE"||c==="INVALID_CODE")return "That code is incorrect or is not the newest code. Request a fresh code and try again.";if(c==="EMAIL_CODE_EXPIRED_OR_NOT_FOUND"||c==="CODE_EXPIRED_OR_NOT_FOUND"||c==="EMAIL_CODE_EXPIRED"||c==="OTP_EXPIRED")return "This verification code has expired. Request a new one.";if(c==="TOO_MANY_ATTEMPTS"||c==="EMAIL_CODE_ATTEMPTS_EXCEEDED"||c==="OTP_ATTEMPTS_EXCEEDED")return "Too many attempts. Please request a new code.";if(c==="ACCOUNT_LINKING_REQUIRED"||c==="ACCOUNT_LINKING_CONFLICT"||c==="EMAIL_LINK_CONFLICT"||c==="LINK_REQUIRED")return "We couldn't safely sign you in with this email. Please use your existing login method or contact WickSpend support.";if(c==="PROVIDER_STATUS_UNKNOWN")return "Your rental is still being confirmed. Check My Rentals shortly.";if(c==="PROVIDER_CANCEL_REJECTED"||c==="NOT_CANCELLABLE"||c==="TEMP_MAIL_NOT_CANCELLABLE")return "This mailbox can no longer be cancelled or refunded.";return SAFE_STATUS_MESSAGES[status]||"We couldn’t complete that request. Please try again."}
export async function wickspendApi<T = unknown>(path:string,options:ApiOptions={}):Promise<T>{const{token,headers,preserveSessionOn401=false,timeoutMs=30000,timeoutMessage="The request took too long. Please try again.",...init}=options;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(`${API_BASE}/${path.replace(/^\//,"")}`,{cache:"no-store",...init,signal:controller.signal,headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{ }),...headers}});const payload=await response.json().catch(()=>null);const pending=response.status===202&&payload&&typeof payload==="object"&&"provider_pending" in payload&&payload.provider_pending===true;if(pending)return payload as T;if(!response.ok||(payload&&typeof payload==="object"&&"ok" in payload&&payload.ok===false)){const code=payload&&typeof payload==="object"&&"code" in payload?String(payload.code):payload&&typeof payload==="object"&&"error" in payload?String(payload.error):undefined;if(response.status===401&&token&&!preserveSessionOn401&&typeof window!=="undefined"){clearSessionTokenIfMatches(token);if(window.location.pathname!=="/login")window.location.assign("/login")}throw new ApiError(response.status,safeMessage(response.status,code),code,payload)}return payload as T}catch(error){if(error instanceof DOMException&&error.name==="AbortError")throw new Error(timeoutMessage);throw error}finally{clearTimeout(timeout)}}
export const newRequestKey=(prefix="web")=>`${prefix}-${typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
const query=(params:Record<string,string|number|undefined>={})=>{const q=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!=="")q.set(k,String(v))});return q.toString()};
// Module-level caches survive App Router page changes, keeping visited screens warm.
const publicCache=new Map<string,{expires:number,value:unknown}>();
const publicInflight=new Map<string,Promise<unknown>>();
function publicGet<T=unknown>(path:string,ttlMs=120000,timeoutMs=30000):Promise<T>{if(typeof window==="undefined")return wickspendApi<T>(path,{timeoutMs});const now=Date.now();const cached=publicCache.get(path);if(cached&&cached.expires>now)return Promise.resolve(cached.value as T);const active=publicInflight.get(path);if(active)return active as Promise<T>;const request=wickspendApi<T>(path,{timeoutMs}).then(value=>{publicCache.set(path,{expires:Date.now()+ttlMs,value});return value}).finally(()=>publicInflight.delete(path));publicInflight.set(path,request as Promise<unknown>);return request}
const privateCache=new Map<string,{expires:number,value:unknown}>();
const privateInflight=new Map<string,Promise<unknown>>();
const privateGeneration=new Map<string,number>();
function privateKey(token:string,path:string){let h=2166136261;for(let i=0;i<token.length;i++){h^=token.charCodeAt(i);h=Math.imul(h,16777619)}return `${(h>>>0).toString(36)}:${path}`}
function invalidatePrivate(token:string,paths:string[]){for(const path of paths){const key=privateKey(token,path);privateGeneration.set(key,(privateGeneration.get(key)||0)+1);privateCache.delete(key);privateInflight.delete(key)}}
function invalidateWalletCache(token:string){invalidatePrivate(token,["wickspend/backend/wallet"]);clearVerifiedBalance(token)}
function walletMutation<T>(token:string,promise:Promise<T>){return promise.then(value=>{invalidateWalletCache(token);invalidatePrivate(token,["wickspend/backend/orders","wickspend/backend/transactions","wickspend/backend/notifications","wickspend/backend/rentals/list"]);return value})}
function privateGet<T=unknown>(path:string,token:string,ttlMs=15000):Promise<T>{const key=privateKey(token,path);const now=Date.now();const cached=privateCache.get(key);if(cached&&cached.expires>now)return Promise.resolve(cached.value as T);const active=privateInflight.get(key);if(active)return active as Promise<T>;const generation=privateGeneration.get(key)||0;const request=wickspendApi<T>(path,{token}).then(value=>{if((privateGeneration.get(key)||0)===generation)privateCache.set(key,{expires:Date.now()+ttlMs,value});return value}).finally(()=>{if(privateInflight.get(key)===request)privateInflight.delete(key)});privateInflight.set(key,request as Promise<unknown>);return request}
function privateFreshGet<T=unknown>(path:string,token:string,ttlMs=15000):Promise<T>{invalidatePrivate(token,[path]);const key=privateKey(token,path);const generation=privateGeneration.get(key)||0;return wickspendApi<T>(path,{token}).then(value=>{if((privateGeneration.get(key)||0)===generation)privateCache.set(key,{expires:Date.now()+ttlMs,value});return value})}
export const api={
 auth:{emailStart:(body:unknown)=>wickspendApi("wickspend/backend/auth/email/request",{method:"POST",body:JSON.stringify(body),timeoutMs:20000}),emailVerify:(body:unknown)=>wickspendApi("wickspend/backend/auth/email/verify",{method:"POST",body:JSON.stringify(body),timeoutMs:20000}),supabaseExchange:(accessToken:string)=>wickspendApi("wickspend/backend/auth/supabase/exchange",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`},body:"{}",preserveSessionOn401:true,timeoutMs:20000}),telegramStart:(body:unknown)=>wickspendApi("wickspend/backend/auth/telegram/request",{method:"POST",body:JSON.stringify(body),timeoutMs:20000}),telegramVerify:(body:unknown)=>wickspendApi("wickspend/backend/auth/telegram/verify",{method:"POST",body:JSON.stringify(body),timeoutMs:20000}),sessionFresh:(token:string)=>wickspendApi("wickspend/backend/auth/session",{token,preserveSessionOn401:true,timeoutMs:10000}),session:(token:string)=>privateGet("wickspend/backend/auth/session",token,30000),logout:(token:string)=>wickspendApi("wickspend/backend/auth/logout",{method:"POST",token,body:"{}"})},
 wallet:{get:(token:string)=>privateGet("wickspend/backend/wallet",token,10000),transactions:(token:string)=>privateGet("wickspend/backend/transactions",token,20000),initializeFunding:(token:string,amount_ngn:number,payment_currency="NGN")=>wickspendApi("wickspend/backend/funding/initialize",{method:"POST",token,body:JSON.stringify({amount_ngn,payment_currency})}),invalidate:(token:string)=>invalidateWalletCache(token)},
 numbers:{catalog:(params:Record<string,string|number|undefined>={})=>{const q=query(params);return publicGet(`wickspend/backend/numbers/catalog${q?`?${q}`:""}`,120000)},countries:(_token?:string)=>publicGet("wickspend/backend/numbers/catalog",120000),services:(_token:string,country_code:string)=>publicGet(`wickspend/backend/numbers/catalog?country_code=${encodeURIComponent(country_code)}`,120000),prices:(_token:string,country_code:string,service_code:string,fresh=false)=>{const path=`wickspend/backend/numbers/catalog?country_code=${encodeURIComponent(country_code)}&service_code=${encodeURIComponent(service_code)}`;if(!fresh)return publicGet(path,120000);publicCache.delete(path);return wickspendApi(path).then(value=>{publicCache.set(path,{expires:Date.now()+120000,value});return value})},buy:(token:string,body:{country_code:string;service_code:string;provider_id?:string;offer_id?:string;operator_id?:string;request_key?:string})=>walletMutation(token,wickspendApi("wickspend/backend/numbers/buy",{method:"POST",token,body:JSON.stringify({...body,request_key:body.request_key||newRequestKey("number")})})),premiumCatalog:(token:string)=>wickspendApi("wickspend/backend/numbers/premium-usa/catalog",{token}),premiumBuy:(token:string,input:{service_code:string;request_key?:string})=>walletMutation(token,wickspendApi("wickspend/numbers/premium-usa/buy",{method:"POST",token,body:JSON.stringify({...input,request_key:input.request_key||newRequestKey("premium-usa")})})),active:(token:string)=>wickspendApi("wickspend/backend/numbers/active",{token}),status:(token:string,reference:string)=>wickspendApi(`wickspend/backend/numbers/status?reference=${encodeURIComponent(reference)}`,{token}),cancel:(token:string,reference:string)=>walletMutation(token,wickspendApi("wickspend/backend/numbers/cancel",{method:"POST",token,body:JSON.stringify({reference})}))},
 rentals:{catalog:()=>publicGet("wickspend/backend/rentals/catalog",120000),carriers:()=>publicGet("wickspend/backend/rentals/carriers",120000),favorites:(token:string)=>privateGet("wickspend/backend/rentals/favorites",token,15000),setFavorite:(token:string,service_code:string,favorite:boolean)=>wickspendApi("wickspend/backend/rentals/favorites",{method:"POST",token,body:JSON.stringify({service_code,favorite})}).then(value=>{invalidatePrivate(token,["wickspend/backend/rentals/favorites"]);return value}),list:(token:string,fresh=false)=>fresh?privateFreshGet("wickspend/backend/rentals/list",token,10000):privateGet("wickspend/backend/rentals/list",token,10000),create:(token:string,input:{service_code:string;duration_minutes:number;country_code:string;carrier_id?:string;area_code?:string;quantity?:number;request_key?:string;expected_price_ngn?:number})=>walletMutation(token,wickspendApi("wickspend/backend/rentals/create",{method:"POST",token,timeoutMs:15000,timeoutMessage:"The request is taking longer than expected. Check My Rentals before trying again.",body:JSON.stringify({country_code:input.country_code,service_code:input.service_code,duration_minutes:input.duration_minutes,carrier_id:input.carrier_id||undefined,area_code:input.area_code||undefined,quantity:input.quantity??1,request_key:input.request_key??newRequestKey("rent"),expected_price_ngn:input.expected_price_ngn})}).then(value=>{invalidatePrivate(token,["wickspend/backend/rentals/list"]);return value})),status:(token:string,reference:string)=>wickspendApi(`wickspend/backend/rentals/status?reference=${encodeURIComponent(reference)}`,{token}),cancel:(token:string,reference:string)=>walletMutation(token,wickspendApi("wickspend/backend/rentals/cancel",{method:"POST",token,body:JSON.stringify({reference})}).then(value=>{invalidatePrivate(token,["wickspend/backend/rentals/list"]);return value})),extend:(token:string,reference:string,request_key=newRequestKey("rent-ext"),target_plan_id?:string)=>walletMutation(token,wickspendApi("wickspend/backend/rentals/extend",{method:"POST",token,body:JSON.stringify({reference,request_key,target_plan_id})}).then(value=>{invalidatePrivate(token,["wickspend/backend/rentals/list"]);return value}))},
 marketplace:{products:(params:Record<string,string|number|undefined>={})=>{const q=query(params);return publicGet(`wickspend/backend/marketplace/products${q?`?${q}`:""}`,300000,12000)},product:(product_id:string)=>publicGet(`wickspend/backend/marketplace/product?product_id=${encodeURIComponent(product_id)}`,300000,15000),reserve:(token:string,input:{product_id:string;quantity?:number;request_key?:string})=>walletMutation(token,wickspendApi("wickspend/backend/marketplace/reserve",{method:"POST",token,body:JSON.stringify({product_id:input.product_id,quantity:input.quantity??1,request_key:input.request_key||newRequestKey("market")})})),orders:(token:string)=>wickspendApi("wickspend/backend/marketplace/orders",{token})},
 boostly:{services:(