import { clearSessionToken } from "@/lib/session";

const API_BASE = (process.env.NEXT_PUBLIC_WICKSPEND_API_BASE || "https://n8n.wickspend.com/webhook").replace(/\/$/, "");
export type ApiOptions = RequestInit & { token?: string | null };
export class ApiError extends Error { status:number; code?:string; payload?:unknown; constructor(status:number,message:string,code?:string,payload?:unknown){super(message);this.name="ApiError";this.status=status;this.code=code;this.payload=payload;} }
const SAFE_STATUS_MESSAGES:Record<number,string>={400:"This sign-in request is invalid or expired. Please try again.",401:"Your session has expired. Please sign in again.",402:"Your wallet balance is too low for this purchase.",409:"This request could not be completed because the item or request state changed.",429:"Too many requests. Please try again shortly.",503:"This service is temporarily unavailable. Please try again later."};
function safeMessage(status:number,code?:string){const c=(code||"").toUpperCase();if(c==="INSUFFICIENT_BALANCE")return SAFE_STATUS_MESSAGES[402];if(c==="INVALID_OR_EXPIRED_SESSION"||c==="UNAUTHORIZED")return SAFE_STATUS_MESSAGES[401];if(c==="EMAIL_NOT_FOUND")return "Unable to send a login code right now. Please try again.";if(c==="INVALID_EMAIL_CODE")return "The verification code is incorrect.";if(c==="EMAIL_CODE_EXPIRED_OR_NOT_FOUND"||c==="EMAIL_CODE_EXPIRED"||c==="OTP_EXPIRED")return "This verification code has expired. Request a new one.";if(c==="TOO_MANY_ATTEMPTS"||c==="EMAIL_CODE_ATTEMPTS_EXCEEDED"||c==="OTP_ATTEMPTS_EXCEEDED")return "Too many attempts. Please request a new code.";if(c==="ACCOUNT_LINKING_CONFLICT"||c==="EMAIL_LINK_CONFLICT"||c==="LINK_REQUIRED")return "We couldn't safely sign you in with this email. Please use your existing login method or contact WickSpend support.";if(c==="PROVIDER_STATUS_UNKNOWN")return "Processing — we’re confirming your order.";return SAFE_STATUS_MESSAGES[status]||"We couldn’t complete that request. Please try again."}
export async function wickspendApi<T = unknown>(path:string,options:ApiOptions={}):Promise<T>{const{token,headers,...init}=options;const response=await fetch(`${API_BASE}/${path.replace(/^\//,"")}`,{cache:"no-store",...init,headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{ }),...headers}});const payload=await response.json().catch(()=>null);const pending=response.status===202&&payload&&typeof payload==="object"&&"provider_pending" in payload&&payload.provider_pending===true;if(pending)return payload as T;if(!response.ok||(payload&&typeof payload==="object"&&"ok" in payload&&payload.ok===false)){const code=payload&&typeof payload==="object"&&"code" in payload?String(payload.code):payload&&typeof payload==="object"&&"error" in payload?String(payload.error):undefined;if(response.status===401&&token&&typeof window!=="undefined"){clearSessionToken();if(window.location.pathname!=="/login")window.location.assign("/login")}throw new ApiError(response.status,safeMessage(response.status,code),code,payload)}return payload as T}
export const newRequestKey=(prefix="web")=>`${prefix}-${typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
const query=(params:Record<string,string|number|undefined>={})=>{const q=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!=="")q.set(k,String(v))});return q.toString()};
export const api={
 auth:{emailStart:(body:unknown)=>wickspendApi("wickspend/backend/auth/email/request",{method:"POST",body:JSON.stringify(body)}),emailVerify:(body:unknown)=>wickspendApi("wickspend/backend/auth/email/verify",{method:"POST",body:JSON.stringify(body)}),telegramStart:(body:unknown)=>wickspendApi("wickspend/backend/auth/telegram/request",{method:"POST",body:JSON.stringify(body)}),telegramVerify:(body:unknown)=>wickspendApi("wickspend/backend/auth/telegram/verify",{method:"POST",body:JSON.stringify(body)}),session:(token:string)=>wickspendApi("wickspend/backend/auth/session",{token}),logout:(token:string)=>wickspendApi("wickspend/backend/auth/logout",{method:"POST",token,body:"{}"})},
 wallet:{get:(token:string)=>wickspendApi("wickspend/backend/wallet",{token}),transactions:(token:string)=>wickspendApi("wickspend/backend/transactions",{token}),initializeFunding:(token:string,amount_ngn:number)=>wickspendApi("wickspend/backend/funding/initialize",{method:"POST",token,body:JSON.stringify({amount_ngn})})},
 numbers:{catalog:(params:Record<string,string|number|undefined>={})=>{const q=query(params);return wickspendApi(`wickspend/backend/numbers/catalog${q?`?${q}`:""}`)},countries:(_token?:string)=>wickspendApi("wickspend/backend/numbers/catalog"),services:(_token:string,country_code:string)=>wickspendApi(`wickspend/backend/numbers/catalog?country_code=${encodeURIComponent(country_code)}`),prices:(_token:string,country_code:string,service_code:string)=>wickspendApi(`wickspend/backend/numbers/catalog?country_code=${encodeURIComponent(country_code)}&service_code=${encodeURIComponent(service_code)}`),buy:(token:string,body:{country_code:string;service_code:string;request_key?:string})=>wickspendApi("wickspend/backend/numbers/buy",{method:"POST",token,body:JSON.stringify({...body,request_key:body.request_key||newRequestKey("number")})}),active:(token:string)=>wickspendApi("wickspend/backend/numbers/active",{token}),status:(token:string,reference:string)=>wickspendApi(`wickspend/backend/numbers/status?reference=${encodeURIComponent(reference)}`,{token}),cancel:(token:string,reference:string)=>wickspendApi("wickspend/backend/numbers/cancel",{method:"POST",token,body:JSON.stringify({reference})})},
 rentals:{catalog:()=>wickspendApi("wickspend/backend/rentals/catalog"),create:(token:string,input:{service_code:string;duration_minutes:1440|4320|10080|20160|43200;country_code?:"US"|"USA";auto_renew?:boolean;request_key?:string})=>wickspendApi("wickspend/backend/rentals/create",{method:"POST",token,body:JSON.stringify({country_code:input.country_code??"US",service_code:input.service_code,duration_minutes:input.duration_minutes,auto_renew:input.auto_renew===true,request_key:input.request_key??newRequestKey("rent")})}),status:(token:string,reference:string)=>wickspendApi(`wickspend/backend/rentals/status?reference=${encodeURIComponent(reference)}`,{token}),cancel:(token:string,reference:string)=>wickspendApi("wickspend/backend/rentals/cancel",{method:"POST",token,body:JSON.stringify({reference})}),extend:(token:string,reference:string,request_key=newRequestKey("rent-ext"))=>wickspendApi("wickspend/backend/rentals/extend",{method:"POST",token,body:JSON.stringify({reference,request_key})})},
 marketplace:{products:(params:Record<string,string|number|undefined>={})=>{const q=query(params);return wickspendApi(`wickspend/backend/marketplace/products${q?`?${q}`:""}`)},product:(product_id:string)=>wickspendApi(`wickspend/backend/marketplace/product?product_id=${encodeURIComponent(product_id)}`),reserve:(token:string,input:{product_id:string;quantity?:number;request_key?:string})=>wickspendApi("wickspend/backend/marketplace/reserve",{method:"POST",token,body:JSON.stringify({product_id:input.product_id,quantity:input.quantity??1,request_key:input.request_key||newRequestKey("market")})}),orders:(token:string)=>wickspendApi("wickspend/backend/marketplace/orders",{token})},
 boostly:{services:(params:Record<string,string|number|undefined>={})=>{const q=query(params);return wickspendApi(`wickspend/backend/boostly/services${q?`?${q}`:""}`)},service:(service_id:string)=>wickspendApi(`wickspend/backend/boostly/service?service_id=${encodeURIComponent(service_id)}`),order:(token:string,input:Record<string,unknown>)=>wickspendApi("wickspend/backend/boostly/order",{method:"POST",token,body:JSON.stringify({...input,request_key:input.request_key||newRequestKey("boostly")})}),orders:(token:string,page=1,limit=20)=>wickspendApi(`wickspend/backend/boostly/orders?page=${page}&limit=${limit}`,{token}),orderDetail:(token:string,reference:string)=>wickspendApi(`wickspend/backend/boostly/order?reference=${encodeURIComponent(reference)}`,{token})},
 tempMail:{services:(search="")=>wickspendApi(`wickspend/backend/temp-mail/services?search=${encodeURIComponent(search)}`),price:(service_code:string)=>wickspendApi(`wickspend/backend/temp-mail/price?service_code=${encodeURIComponent(service_code)}`),order:(token:string,input:Record<string,unknown>)=>wickspendApi("wickspend/backend/temp-mail/order",{method:"POST",token,body:JSON.stringify({...input,request_key:input.request_key||newRequestKey("mail")})}),status:(token:string,reference:string)=>wickspendApi(`wickspend/backend/temp-mail/order?reference=${encodeURIComponent(reference)}`,{token}),cancel:(token:string,reference:string)=>wickspendApi("wickspend/backend/temp-mail/cancel",{method:"POST",token,body:JSON.stringify({reference})}),orders:(token:string,page=1,limit=20)=>wickspendApi(`wickspend/backend/temp-mail/orders?page=${page}&limit=${limit}`,{token})},
 orders:(token:string)=>wickspendApi("wickspend/backend/orders",{token}),
 notifications:{list:(token:string)=>wickspendApi("wickspend/backend/notifications",{token}),markRead:(token:string,notification_id:string|number)=>wickspendApi("wickspend/backend/notifications/read",{method:"POST",token,body:JSON.stringify({notification_id})}),markAllRead:(token:string)=>wickspendApi("wickspend/backend/notifications/read",{method:"POST",token,body:JSON.stringify({all:true})})},
 support:{chat:(token:string,message:string)=>wickspendApi("wickspend/backend/support/chat",{method:"POST",token,body:JSON.stringify({message})})}
};