// Generated from the public service table documented by the catalog provider.
// Keep this local so provider details never have to be sent to the browser.
export const NUMBER_SERVICE_NAMES: Readonly<Record<string, string>> = {
  "aa": "Probo",
  "aab": "BharatPe",
  "aag": "Pockit",
  "aap": "Tiptapp",
  "aaq": "Netease",
  "aar": "Bearwww",
  "aas": "XXGame",
  "aau": "RockeTreach",
  "aav": "Alchemy",
  "aaw": "Aya Bank",
  "aax": "Boyaa",
  "aay": "JioMart",
  "aaz": "Ozan",
  "ab": "Alibaba",
  "aba": "Rappi",
  "abb": "Coca-Cola",
  "abc": "Taptap Send",
  "abd": "Beboo",
  "abe": "Foodora",
  "abi": "BytePlus",
  "abk": "GMX",
  "abn": "Namars",
  "abo": "WEBDE",
  "abq": "Upwork",
  "abr": "Privy",
  "abs": "Playerzpot",
  "abt": "ArenaPlus",
  "abu": "BPJSTK",
  "abx": "Kaching",
  "aby": "Couponscom",
  "abz": "Friendtech",
  "ac": "DoorDash",
  "acb": "Spark Driver",
  "acc": "LuckyLand Slots",
  "acd": "CheckDomain",
  "ace": "Tata Neu",
  "acf": "Winter Loan",
  "acg": "CollabAct",
  "ach": "Haleon",
  "acj": "Meituan",
  "ack": "Tomato",
  "acl": "Tiv",
  "acm": "Razer",
  "acn": "Radium",
  "aco": "AR Lens",
  "acp": "BonusLink",
  "acq": "Suntec",
  "acr": "QwikCilver",
  "acs": "Tata CLiQ Palette",
  "acu": "CityMall",
  "acv": "A23",
  "acy": "Airtime",
  "acz": "Claude",
  "ad": "Iti",
  "ada": "TRUTH SOCIAL",
  "adb": "PoshVine",
  "adc": "PlayOJO",
  "ade": "Magicpin",
  "adf": "BCA Syariah",
  "adg": "Marwadi",
  "adh": "Frizza",
  "adi": "Zepto",
  "adj": "RummyCircle",
  "adk": "Khatabook",
  "adl": "EarnEasy",
  "adm": "FitCredit",
  "adn": "Zach Bryan",
  "ado": "SmartyPig",
  "adp": "Cabify",
  "adq": "Uzum",
  "ads": "GoChat",
  "adt": "Willhaben",
  "adu": "Seznam",
  "adx": "BusyFly",
  "ae": "MyGLO",
  "aeb": "GoPayz",
  "aec": "JinJiang",
  "aed": "Kamatera",
  "aei": "Tanoti",
  "ael": "Cloud Manager",
  "aem": "AstraPay",
  "aen": "Redigame",
  "aeo": "Allofresh",
  "aep": "ONBUKA",
  "aeq": "Godrej",
  "aer": "PlayerAuctions",
  "aet": "Greywoods",
  "aeu": "TheFork",
  "aev": "BankKaro",
  "aew": "Flip",
  "aex": "Neon",
  "aez": "Shein",
  "af": "GalaxyWin",
  "afb": "Maybank",
  "afc": "Bunda",
  "afd": "Astra Otoshop",
  "afj": "SKCAPITAL",
  "afk": "Chevron",
  "afm": "Myboost",
  "afn": "Roomster",
  "afp": "VFS GLOBAL",
  "aft": "Neocrypto",
  "afw": "Packeta",
  "afx": "Gamesofa",
  "afy": "Tuul",
  "afz": "Klarna",
  "aga": "Publi24",
  "agb": "Smiles",
  "agc": "VIMpay",
  "agd": "Grailed",
  "age": "MTR Mobile",
  "agf": "Meitu",
  "agg": "OneForma",
  "agh": "Anibis",
  "agi": "Njuškalo",
  "agj": "Marktplaats",
  "agk": "Ipsos iSay",
  "agl": "Betano",
  "agm": "CMB",
  "agn": "Flik",
  "ago": "Servify",
  "agp": "Hdfcbank",
  "agq": "Bajaj Finserv",
  "agr": "Yonogames",
  "ags": "Abbott",
  "agu": "Story Max",
  "agx": "MeiQFashion",
  "agy": "Baihe",
  "agz": "Jiva Petani",
  "aha": "Angel One",
  "ahb": "Ubisoft",
  "ahd": "OpenPhone",
  "ahe": "Bunq",
  "ahf": "Fugeelah",
  "ahi": "Daki",
  "ahj": "Strato",
  "ahk": "БлинБери",
  "ahm": "BRO",
  "aho": "UangMe",
  "ahp": "PizzaHut",
  "ahq": "SEEDS",
  "ahr": "This Fate",
  "ahs": "1and1",
  "aht": "MockGuru",
  "ahv": "Surveybell",
  "ahw": "Zasilkovna",
  "ahx": "Bitrue",
  "ahy": "Fliff",
  "ai": "CELEBe",
  "aid": "Kia",
  "aif": "Royal Canin",
  "aig": "K11",
  "aih": "Fups",
  "aii": "Hinge Dating",
  "aij": "NEQUI",
  "aik": "ZUS Coffee",
  "ail": "Zoo Game",
  "ain": "SpaceWeb",
  "aio": "Prakerja",
  "aip": "AfreecaTV",
  "aiq": "Prime Opinion",
  "air": "TipTip",
  "ais": "Schibsted",
  "ait": "FeetFinder",
  "aiv": "Striving in the Lion City",
  "aix": "Move It",
  "aiy": "Nloto",
  "aiz": "Brevo",
  "aj": "OneAset",
  "aja": "G2A",
  "ajd": "Bankera",
  "aje": "CupidMedia",
  "ajf": "IPanelOnline",
  "ajg": "Fortumo",
  "ajh": "WAUG",
  "ajj": "Rebtel",
  "ajk": "Venteny",
  "ajl": "Av100pro",
  "ajm": "Gener8",
  "ajn": "Gopuff",
  "ajo": "CoffeeTea",
  "ajp": "AsiaMiles",
  "ajq": "MyValue",
  "ajr": "Boku",
  "ajs": "GetPlus",
  "aju": "Daya Auto",
  "ajv": "ShareParty",
  "ajw": "INDOBA",
  "ajx": "Kemnaker RI",
  "ajy": "All Access",
  "ajz": "MotionPay",
  "ak": "Douyu",
  "aka": "LinkAja",
  "akb": "Gurmanika",
  "akc": "Paybis",
  "akd": "Feels",
  "ake": "DIKIDI",
  "akf": "Ollis",
  "akg": "Book My Play",
  "akh": "Prenagen Club",
  "aki": "Tiketcom",
  "akj": "Easycash",
  "akk": "Dagangan",
  "akl": "DOKU",
  "akm": "LOTTE Mart",
  "akn": "Chakra Rewards",
  "ako": "Ryde",
  "akp": "Her",
  "akq": "Blank Street",
  "akr": "Voi",
  "aks": "Hanya",
  "akt": "Xworldwallet",
  "akw": "WINDS",
  "akx": "Sony LIV",
  "aky": "GOMOFY",
  "ala": "GetResponse",
  "ald": "Nice88",
  "ale": "Lydia",
  "alg": "Ankama",
  "alh": "Lion Parcel",
  "ali": "StockyDodo",
  "alj": "Spotify",
  "alm": "Muzz",
  "aln": "Remotasks",
  "alo": "Profee",
  "alp": "Mera Gaon",
  "als": "Greggs",
  "alt": "Segari",
  "alu": "BC Game",
  "alv": "TIER",
  "alw": "Vida",
  "alx": "NutriClub",
  "aly": "Bebeclub",
  "am": "Amazon",
  "ama": "WooPlus",
  "amb": "Vercel",
  "amd": "Smart",
  "ame": "Discover Hong Kong",
  "amf": "Acko",
  "amg": "SBI Card",
  "amh": "MitID",
  "ami": "TEAMORU",
  "amk": "GORDAN",
  "aml": "Xbox",
  "amm": "Punjab citizen",
  "amp": "Timepass",
  "amt": "Moneyview",
  "an": "Adidas",
  "anc": "VARUS",
  "ane": "Supercell",
  "ani": "Talabat",
  "ao": "UU163",
  "aoa": "Hicard",
  "aof": "Guzman y Gomez",
  "aog": "Naukri",
  "aos": "Loloo",
  "apa": "Exness",
  "apl": "Sideline",
  "apr": "Capital One",
  "aprnt": "theAsianparent",
  "aptn": "Aspiration",
  "aq": "Glovo",
  "aqj": "BigBasket",
  "ar": "Wondermart",
  "ari": "Ring4",
  "ars": "Bingoplus",
  "asj": "T-Online",
  "at": "Perfluence",
  "au": "Haraj",
  "aud": "Audible",
  "auw": "3Fun",
  "aux": "Lightning AI",
  "auz": "Outlier",
  "avb": "Tealive",
  "avk": "Quoka",
  "avt": "Aviata.kz",
  "avz": "Getsbet",
  "aw": "Taikang",
  "awg": "Natura Avon",
  "awq": "Atlas Earth",
  "aws": "Aws",
  "awv": "Wallapop",
  "awz": "PlayTime",
  "ax": "CrefisaMais",
  "axr": "match.com",
  "ay": "Ruten",
  "ayc": "HungerStation",
  "ayk": "Radquest",
  "ayz": "Kimi",
  "az": "CityBase",
  "ba": "Expressmoney",
  "baq": "Redbubble",
  "bb": "LazyPay",
  "bbf": "Neosurf",
  "bbm": "Truemoney",
  "bc": "GCash",
  "bcq": "Kopi Kenangan",
  "bcw": "KodBende",
  "bdp": "Kredito",
  "bdx": "Benjamin",
  "bex": "Whatnot",
  "bf": "Keybase",
  "bff": "Buff.163",
  "bfl": "Black Forest Labs",
  "bg": "MIXMART",
  "bgf": "Rapido",
  "bhi": "Chase",
  "bhl": "Ati.su",
  "bhz": "Eurobet",
  "bi": "勇仕网络Ys4fun",
  "bk": "G2G",
  "bl": "Bigo Live",
  "blb": "foundit",
  "blbk": "Blastbucks",
  "ble": "NEXON",
  "blr": "DocuSign",
  "bm": "MarketGuru",
  "bmi": "Sisal",
  "bmj": "Betflag",
  "bn": "Alfagift",
  "bnl": "Reddit",
  "bnn": "Binance",
  "bnu": "Qpon",
  "bo": "Wise",
  "boc": "51exch",
  "bol": "Bosslike",
  "boo": "CasinoPlus",
  "bou": "汇旺 Huione Pay",
  "bp": "GoFundMe",
  "bpc": "LOVOO",
  "bq": "Adani",
  "bqe": "Lottomatica",
  "bqy": "SNAI",
  "bqz": "Credit Karma",
  "brg": "Letgo",
  "brh": "Efsane",
  "brnc": "Branch",
  "brt": "Netwin",
  "bs": "TradeUP",
  "bsw": "Milanuncios",
  "bt": "Alfa",
  "btnn": "BETININ",
  "bu": "MonobankIndia",
  "busq": "Busqo",
  "bva": "Bingo101",
  "bw": "Signal",
  "bwb": "Winmatch",
  "bx": "Dosi",
  "byh": "Adobe",
  "bz": "Blizzard",
  "bzb": "Big Cash",
  "ca": "SuperS",
  "cb": "Bazos",
  "cc": "Quipp",
  "ccv": "Triumph",
  "cdy": "Caddy",
  "cf": "irancell",
  "cf_id": "CoinFantasy",
  "cg": "Gemgala",
  "cgp": "College Pulse",
  "ch": "Pocket52",
  "ci": "redBus",
  "cim": "Acima",
  "cj": "Dotz",
  "ck": "BeReal",
  "cl": "UWIN",
  "clg": "Clubgg",
  "cm": "Prom",
  "cn": "Fiverr",
  "co": "Rediffmail",
  "cp": "Uklon",
  "cpt": "Chipotle",
  "cq": "Mercado",
  "cr": "TenChat",
  "crsr": "Cursor",
  "cs": "AgriDevelop",
  "ctd": "Courtyard",
  "ctkt": "ConfirmTkt",
  "ctr": "CenturyLink",
  "cu": "炙热星河",
  "cv": "WashXpress",
  "cw": "PaddyPower",
  "cwg": "CWG",
  "cx": "Icrypex",
  "cz": "Getmega",
  "dah": "DahaDaha",
  "dav": "Dave",
  "daz": "LODA",
  "db": "ezbuy",
  "dc": "YikYak",
  "dd": "CloudChat",
  "den": "FriendshipHub",
  "df": "Happn",
  "dg": "Mercari",
  "dgo": "DigitalOcean",
  "dh": "Ebay",
  "di": "Loanflix",
  "ding": "ding",
  "dk": "Pairs",
  "dl": "Lazada",
  "dm": "Iwplay",
  "dn": "Paxful",
  "do": "Leboncoin",
  "dp": "Protonmail",
  "dps": "FDJ Parions Sport",
  "dr": "OpenAI (ChatGPT)",
  "ds": "Discord",
  "dt": "Delivery Club",
  "dtc": "Dutch Bros",
  "du": "AUBANK",
  "dv": "NoBroker",
  "dw": "Divar",
  "dx": "Powerkredite",
  "dy": "Zomato",
  "dz": "Dominos Pizza",
  "ea": "JamesDelivery",
  "eb": "Voltz",
  "ebay_kl": "Kleinanzeigen",
  "ec": "RummyCulture",
  "ed": "Gamer",
  "edo": "RusDate",
  "ee": "Twilio",
  "ef": "Nextdoor",
  "eg": "ContactSys",
  "ei": "Taksheel",
  "ej": "MrQ",
  "el": "Bisu",
  "els": "Nielsen",
  "em": "ZéDelivery",
  "en": "Hermes",
  "enu": "Emenu",
  "eo": "Sizeer",
  "ep": "Temu",
  "eq": "Qoo10",
  "er": "Kwork",
  "es": "iQIYI",
  "esz": "Ez777",
  "et": "Clubhouse",
  "etsy": "Etsy",
  "eu": "LiveScore",
  "ev": "Picpay",
  "eve": "Enilive",
  "ew": "Nike",
  "ex": "Linode",
  "ey": "miloan",
  "ez": "GoerliFaucet",
  "fa": "XadrezFeliz",
  "facebook": "Facebook",
  "fb": "Facebook",
  "fc": "PharmEasy",
  "fe": "CliQQ",
  "fed": "Cline",
  "fg": "IndianOil",
  "fh": "Lalamove",
  "fi": "Dundle",
  "fj": "Potato Chat",
  "fk": "BLIBLI",
  "fl": "RummyLoot",
  "fm": "Touchance",
  "fmc": "FMCPay",
  "fo": "MobiKwik",
  "fog": "Flamingo",
  "fp": "Phound",
  "fpx": "500px",
  "fr": "DANA",
  "fs": "Şikayet var",
  "fst": "Fastwin",
  "fu": "Snapchat",
  "full": "Full rent",
  "fv": "Vidio",
  "fvss": "fivesurveys",
  "fw": "99acres",
  "fx": "Pgbonus",
  "fy": "Mylove",
  "fyt": "Cityflo",
  "fz": "KFC",
  "ga": "Roposo",
  "gah": "Pazarama",
  "gal": "Goldbet",
  "gb": "YouStar",
  "gc": "TradingView",
  "gd": "Surveytime",
  "ge": "Paytm",
  "gf": "GoogleVoice",
  "gg": "PagSmile",
  "ggms": "Goa games",
  "gh": "GyFTR",
  "ghe": "GetHoldings",
  "ght": "Google Chat",
  "gi": "Hotline",
  "git": "GitHub",
  "gj": "Carousell",
  "gl": "GlobalTel",
  "gm": "Mocospace",
  "gmsg": "Google Messenger",
  "gmy": "BridgeMoney",
  "gn": "A9A",
  "gnt": "Gaintplay",
  "go": "Google, Gmail, Youtube",
  "google": "Google / Gmail",
  "gor": "Redrob Signal",
  "gp": "Ticketmaster",
  "gq": "Freelancer",
  "gr": "Astropay",
  "gr_bf": "Beanfun",
  "gr_bg": "Battlestate Games",
  "gr_rd": "Chalkboard",
  "gr_tl": "Tilda",
  "grk": "Grok",
  "gs": "SamsungShop",
  "gt": "Gett",
  "gu": "Fora",
  "guc": "SwagBucks",
  "gun": "Hungry Panda",
  "guv": "Guvi",
  "gv": "Humta",
  "gvc": "Zoom",
  "gw": "CallApp",
  "gx": "Hepsiburadacom",
  "gy": "MIYACHAT",
  "gyt": "BetExc",
  "gz": "LYKA",
  "ha": "My11Circle",
  "hb": "Twitch",
  "hc": "MOMO",
  "hd": "MarketPapa",
  "hdfc": "HDFC Egro",
  "hdt": "Hindustan",
  "he": "Mewt",
  "hep": "HeyPiggy",
  "hf": "Cleartrip",
  "hg": "Switips",
  "hh": "Uplay",
  "hi": "JungleeRummy",
  "hj": "Nykaa",
  "hk": "4FunLite",
  "hl": "Band",
  "hm": "Globus",
  "hn": "1688",
  "ho": "Cathay",
  "hp": "Meesho",
  "hpnc": "Happypancake",
  "hq": "Magicbricks",
  "hr": "JKF",
  "hra": "Aadhar",
  "hrnjie": "华人街",
  "hs": "Asda",
  "ht": "Bitso",
  "htv": "Hotlive",
  "hu": "Ukrnet",
  "hug": "Driv&",
  "hw": "AliPay",
  "hx": "AliExpress",
  "hy": "Ininal",
  "hyp": "Hypermart",
  "ia": "Socios",
  "ib": "Immowelt",
  "ibt": "Ibotta",
  "ic": "JoGo",
  "ido": "Idee Opinioni",
  "idr": "FDA",
  "ig": "Instagram",
  "ih": "TeenPattiStarpro",
  "ii": "CashKaro",
  "ij": "Revolut",
  "il": "IQOS",
  "im": "IMO messenger",
  "instagram": "Instagram",
  "ioy": "Rupiyo",
  "ip": "Burger King",
  "iq": "icq",
  "ir": "Chispa",
  "it": "CashApp",
  "iu": "Bykea",
  "iv": "Inboxlv",
  "ix": "Celcoin",
  "iy": "FoodHub",
  "iz": "Global24",
  "ja": "Weverse",
  "jau": "Jiagu360",
  "jb": "Wing Money",
  "jd": "GiraBank",
  "jdz": "Hopegoo",
  "je": "Nanovest",
  "jf": "Likee",
  "jg": "Grab",
  "jh": "PingPong",
  "ji": "Monobank",
  "jj": "Aitu",
  "jl": "Hopi",
  "jm": "mzadqatar",
  "jno": "Juno",
  "jq": "Paysafecard",
  "jt": "TurkiyePetrolleri",
  "ju": "Indomaret",
  "jw": "Br777",
  "jwc": "Jalwa Game",
  "jx": "Swiggy",
  "jy": "Sorare",
  "jz": "Kaya",
  "ka": "Shopee",
  "kac": "Chick Fil A",
  "kb": "kufarby",
  "kc": "Vinted",
  "kch": "KickCash",
  "kck": "Kick",
  "kds": "Kudos",
  "ke": "Эльдорадо",
  "keet": "Keeta",
  "kf": "Weibo",
  "kg": "FreeChargeApp",
  "kh": "Bukalapak",
  "ki": "99app",
  "kiq": "Kliq",
  "kir": "Predik",
  "kj": "YAPPY",
  "kk": "Idealista",
  "kl": "kolesa.kz",
  "klb": "Kolotibablo",
  "km": "Rozetka",
  "kn": "Verse",
  "kny": "Konvy",
  "ko": "AdaKami",
  "kon": "Monkey",
  "kp": "HQ Trivia",
  "kq": "FotoCasa",
  "kr": "Eyecon",
  "ks": "Hirect",
  "kt": "KakaoTalk",
  "ku": "RoyalWin",
  "kv": "Rush",
  "kvb": "KVB",
  "kw": "Foody",
  "kx": "Vivo",
  "ky": "SpatenOktoberfest",
  "kz": "NimoTV",
  "la": "ssoidnet",
  "lc": "Subito",
  "ld": "Cashmine",
  "ldps": "ludoplus",
  "le": "E bike Gewinnspiel",
  "lf": "Tiktok",
  "lg": "MediBuddy",
  "li": "Baidu",
  "lid": "Ludo Winner",
  "lj": "Santander",
  "lk": "PurePlatfrom",
  "lmd": "Ashley Madison",
  "ln": "Grofers",
  "lo": "OPPO",
  "log": "Long Chau",
  "lp": "Algida",
  "lq": "Potato",
  "lr": "Okta",
  "lrmn": "LEROY MERLIN",
  "ls": "Careem",
  "lt": "Bitclout",
  "lu": "Crickpe",
  "luf": "Luckin Coffee",
  "lw": "MrGreen",
  "lx": "DewuPoison",
  "ly": "Olacabs",
  "lz": "Things",
  "max": "MAX",
  "mb": "Yahoo",
  "mc": "MiChat",
  "mcr": "MYCAR.KZ",
  "me": "LINE",
  "meb": "MBMBet",
  "meex": "Media express",
  "mf": "Weidian",
  "mgrs": "Migros",
  "mi": "Zupee",
  "mj": "Zalo",
  "mk": "LongHu",
  "ml": "ApostaGanha",
  "mlk": "Mackolik",
  "mln": "Mulerun",
  "mm": "Microsoft",
  "mml": "MMLive",
  "mn": "RRSA",
  "mo": "Bumble",
  "mp": "Winmasters",
  "mq": "GMNG",
  "mr": "Fastmail",
  "ms": "NovaPoshta",
  "mt": "Steam",
  "mu": "MyMusicTaste",
  "mua": "meta.ua",
  "mv": "Fruitz",
  "mw": "Transfergo",
  "mx": "SoulApp",
  "my": "CAIXA",
  "nc": "Payoneer",
  "ne": "Coindcx",
  "nf": "Netflix",
  "ng": "FunPay",
  "nh": "AlloBank",
  "ni": "Gojek",
  "niu": "MILKRUN",
  "nk": "Gittigidiyor",
  "nm": "Thisshop",
  "nmcr": "Namaskar",
  "nmkz": "Naimi.kz",
  "nn": "Giftcloud",
  "nne": "OneOne",
  "no": "Virgo",
  "np": "Siply",
  "nq": "Trip",
  "nr": "Tosla",
  "ns": "Oldubil",
  "nst": "Instamatch",
  "ntp": "NextOtp",
  "nu": "Stripe",
  "nuum": "Nuum.ru",
  "nv": "Naver",
  "nw": "Ximalaya",
  "ny": "Pyro Music",
  "nz": "Foodpanda",
  "ob": "Onlinerby",
  "ob_uz": "OpenBudjet",
  "oc": "DealShare",
  "od": "FWDMAX",
  "odl": "Ricardo",
  "oe": "Codashop",
  "oh": "MapleSEA",
  "oha": "AstroChat",
  "oi": "Tinder",
  "oji": "Ajio",
  "olxbg": "OLXbg",
  "olxkz": "OLXkz",
  "olxpl": "OLXpl",
  "olxpt": "OLXpt",
  "olxro": "OLXro",
  "olxua": "OLXua",
  "olxuz": "OLXuz",
  "om": "Corona",
  "omx": "Angi",
  "oo": "LigaPro",
  "opd": "Poe",
  "oq": "Vlife",
  "os": "Dhani",
  "ot": "Any Other",
  "otk": "51game",
  "otr": "Story TV",
  "oty": "Jaya Slot",
  "ou": "Gabi",
  "owp": "Owlproxy",
  "ox": "Damejidlo",
  "oxh": "Oxinchain",
  "oy": "CashFly",
  "oz": "Poshmark",
  "pa": "Gamekit",
  "pb": "SkyTV",
  "pc": "Casino, bet, gambling",
  "pcp": "Pcipay",
  "pd": "IFood",
  "pev": "WPlace",
  "pf": "Plenty of Fish",
  "ph": "SnappFood",
  "pkr": "Playkaro247",
  "pla": "PolloAI",
  "plg": "Pelago",
  "pm": "AOL",
  "pmv": "Prime video",
  "po": "premium.one",
  "pon": "Pokemon",
  "pp": "Huya",
  "ppl": "PYYPL",
  "pq": "CDkeys",
  "pr": "Trendyol",
  "prcl": "Poker Circle",
  "pt": "Bitaqaty",
  "pts": "Piattos",
  "pu": "Justdating",
  "pw": "SellMonitor",
  "px": "Nifty",
  "py": "Monese",
  "pz": "Lidl",
  "pzr": "Paisabazaar",
  "qaf": "Cred",
  "qb": "Payberry",
  "qbk": "First Games",
  "qbn": "RummyYes",
  "qbs": "Sixer",
  "qcb": "Shopsy",
  "qcx": "Narendra modi",
  "qcz": "Creditmantri",
  "qd": "Taobao",
  "qdx": "Truemeds",
  "qe": "GG",
  "qf": "RedBook",
  "qff": "Aditya birla",
  "qg": "MoneyPay",
  "qgh": "Indiapolls",
  "qhb": "Dot and Key",
  "qhp": "CheQ",
  "qhy": "Omnicard",
  "qi": "32Red",
  "qim": "HPGas",
  "qit": "Royaljeet",
  "qiv": "Goldsbet",
  "qiy": "Saathi",
  "qjb": "Okwin",
  "qjm": "Cricbuzz",
  "qjp": "Innopay",
  "qjw": "Shriram One",
  "qk": "Bit",
  "qkp": "Quarkip",
  "qks": "Winclash",
  "qkt": "SpinWinner",
  "qkz": "Govinda365",
  "ql": "CMTcuzdan",
  "qld": "Ludo11",
  "qly": "Woohoo",
  "qmf": "Dream Money",
  "qml": "Ranglive",
  "qmp": "Tata Motors",
  "qmq": "QuickTv",
  "qn": "Blued",
  "qq": "Tencent QQ",
  "qql": "QQLive",
  "qr": "MEGA",
  "qrr": "Roz Rummy",
  "qt": "MoneyСontrol",
  "qx": "WorldRemit",
  "qy": "Zhihu",
  "qz": "Faceit",
  "qzn": "Qzino",
  "ra": "KeyPay",
  "rap": "RapidApi",
  "rb": "Tick",
  "rc": "Skype",
  "rch": "Research 360",
  "rf": "Akudo",
  "rh": "Ace2Three",
  "ri": "BillMill",
  "rk": "Fotka",
  "rktn": "Rakuten",
  "rl": "inDriver",
  "rn": "neftm",
  "ro": "PingCode",
  "rp": "hamrahaval",
  "rr": "Wolt",
  "rs": "Lotus",
  "rsy": "Resy",
  "rt": "hily",
  "ru": "HOP",
  "rv": "Kotak811",
  "rw": "BLS-SPAIN",
  "rx": "Sheerid",
  "ry": "McDonalds",
  "rz": "EasyPay",
  "sa": "AGIBANK",
  "saj": "Raja Games",
  "satu_kz": "Satu",
  "sc": "Voggt",
  "scrf": "Scruff",
  "se": "Feeld",
  "ser": "SerpApi",
  "sf": "SneakersnStuff",
  "sgk": "SeatGeek",
  "sht": "ShareChat",
  "si": "Cita Previa",
  "sj": "HandyPick",
  "sk": "Skroutz",
  "skls": "Skills",
  "sli": "Sponline",
  "sls": "Streamlabs",
  "sm": "YoWin",
  "sn": "OLX",
  "snl": "Sonol",
  "so": "RummyWealth",
  "sp": "HappyFresh",
  "sq": "KuCoinPlay",
  "sr": "Starbucks",
  "sre": "Starexch",
  "ss": "Hezzl",
  "std": "Seated",
  "stn": "Stan",
  "su": "LOCO",
  "sw": "NCsoft",
  "swl": "Swarail",
  "sx": "Crowdtap",
  "sy": "Brahma",
  "talk": "Talkatone",
  "tbn": "TurboTenant",
  "tcw": "Switchere",
  "td": "ChaingeFinance",
  "te": "eFood",
  "telegram": "Telegram",
  "tf": "Noon",
  "tg": "Telegram",
  "ti": "cryptocom",
  "tiktok": "TikTok",
  "tis": "WinMate",
  "tit": "TIM IT",
  "tj": "dbrUA",
  "tjrm": "Taj Rummy",
  "tks": "Tiktok shop",
  "tl": "Truecaller",
  "tln": "Toluna",
  "tm": "Akulaku",
  "tme": "OurTime",
  "tmi": "Taimi",
  "tmro": "Tomoro Coffee",
  "tmw": "Timewall",
  "tn": "LinkedIn",
  "tnst": "Tune studio",
  "tnx": "Telnyx",
  "tod": "TheDermaCo",
  "tp": "IndiaGold",
  "tq": "Swvl",
  "tr": "Paysend",
  "trc": "TrapCall",
  "ts": "PayPal",
  "tsp": "Trustpilot",
  "tt": "Ziglu",
  "ttm": "TextMe",
  "ttn": "Textnow",
  "tu": "Lyft",
  "tui": "Tutti",
  "tum": "Tumblr",
  "tv": "Flink",
  "tw": "Twitter",
  "tx": "Bolt",
  "ub": "Uber",
  "ubr_gr": "Universal Beijing Resort",
  "ud": "Disney Hotstar",
  "ue": "Onet",
  "uf": "Eneba",
  "ug": "Fiqsy",
  "uh": "Yubo",
  "ui": "RuTube",
  "uj": "СhampionСasino",
  "uk": "AirBnb",
  "ul": "Getir",
  "ume": "Premium Bandai",
  "un": "Humble bundle",
  "uns": "Unstop",
  "uo": "CafeBazaar",
  "uq": "TopDetal",
  "ur": "MyDailyCash",
  "us": "IRCTC",
  "usp": "Australia Post",
  "uta": "BEUTEA",
  "uv": "BinBin",
  "uw": "Kirana",
  "uy": "Meliuz",
  "uz": "OffGamers",
  "va": "SportGully",
  "vc": "Banqi",
  "ve": "Dream11",
  "vf": "Q12 Trivia",
  "vg": "ShellBox",
  "vi": "Viber",
  "vj": "Stormgain",
  "vk": "ВК, Одноклассники, Юла (mail.ru group)",
  "vm": "Okcupid",
  "vn": "Yaay",
  "vnd": "WOW88",
  "vo": "Brand20ua",
  "vp": "Kwai",
  "vq": "LadyMaria",
  "vr": "MotorkuX",
  "vrst": "Verasight",
  "vs": "WinzoGame",
  "vsn": "Vision11",
  "vv": "Seo Sprint",
  "vw": "CoinField",
  "vx": "HeyBox",
  "vy": "Meta",
  "vz": "Hinge",
  "wa": "WhatsApp",
  "wb": "WeChat",
  "wc": "Craigslist",
  "wfargo": "Wells Fargo",
  "wfo": "Ownly",
  "wg": "Skout",
  "wh": "TanTan",
  "whatsapp": "WhatsApp",
  "wj": "1xbet",
  "wk": "Mobile01",
  "wku": "WorkUA",
  "wl": "YouGotaGift",
  "wmb": "Wamba",
  "wmpl": "Womply",
  "wn": "GameArena",
  "wnd": "Windsurf",
  "wo": "Parkplus",
  "wp": "163СOM",
  "wq": "Leboncoin1",
  "wr": "Walmart",
  "ws": "Indodax",
  "wt": "IZI",
  "wu": "PrivetMir",
  "wv": "AIS",
  "ww": "BIP",
  "wx": "Apple",
  "wy": "Yami",
  "wz": "FoxFord",
  "xb": "RummyOla",
  "xc": "SynotTip",
  "xd": "Tokopedia",
  "xe": "GalaxyChat",
  "xf": "LightChath",
  "xg": "FortunaSK",
  "xgu": "RedNote / Xiaohongshu",
  "xh": "Ovo",
  "xi": "InFund",
  "xk": "DiDi taxi",
  "xl": "Wmaraci",
  "xn": "Familia",
  "xo": "Notifire",
  "xq": "MPL",
  "xr": "Tango",
  "xs": "GroupMe",
  "xu": "RecargaPay",
  "xv": "Wish",
  "xw": "Taki",
  "xx": "Joyride",
  "xy": "Depop",
  "xz": "paycell",
  "yab": "Brevistay",
  "yd": "米画师Mihuashi",
  "yg": "CourseHero",
  "yi": "Yemeksepeti",
  "yj": "eWallet",
  "yl": "Yalla",
  "ylww": "Yellow",
  "yn": "Allegro",
  "yo": "Amasia",
  "yoho": "YoHo",
  "yp": "Payzapp",
  "yr": "Miravia",
  "ys": "ZCity",
  "yto": "Anna Lottery",
  "yu": "Xiaomi",
  "yudafr": "Yuda",
  "yv": "IPLwin",
  "yw": "Grindr",
  "yx": "JTExpress",
  "yy": "Venmo",
  "za": "Jingdong",
  "zb": "FreeNow",
  "zd": "Zilch",
  "ze": "Shpock",
  "zf": "OnTaxi",
  "zg": "Setel",
  "zh": "Zoho",
  "zi": "LoveLocal",
  "zj": "ROBINHOOD",
  "zk": "Deliveroo",
  "zl": "Airtel",
  "zlw": "Zillow",
  "zm": "OfferUp",
  "zmx": "Zenmux",
  "zn": "Biedronka",
  "zo": "Kaggle",
  "zp": "Pinduoduo",
  "zq": "IndiaPlays",
  "zr": "Papara",
  "zs": "Bilibili",
  "zt": "Budweiser",
  "zu": "BigC",
  "zv": "Digikala",
  "zw": "Quack",
  "zx": "CommunityGaming",
  "zy": "Nttgame",
  "zz": "DENT",
};
