"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {api,newRequestKey} from "@/lib/api";
import {getSessionToken} from "@/lib/session";

type UserRow={id:number|string;name?:string;email?:string|null;telegram_user_id?:number|string|null;balance_ngn?:number|string;created_at?:string;last_seen_at?:string|null;transaction_count?:number|string};
const money=(v:unknown)=>`₦${Number(v||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const when=(v?:string|null)=>v?new Date(v).toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"}):"Never";

export default function AdminUsers(){
 const[query,setQuery]=useState("");const[rows,setRows]=useState<UserRow[]>([]);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[selected,setSelected]=useState<UserRow|null>(null);const[action,setAction]=useState<"credit"|"debit">("credit");const[amount,setAmount]=useState("");const[reason,setReason]=useState("");const[busy,setBusy]=useState(false);
 async function load(search=query){const token=getSessionToken();if(!token){setMessage("Admin session required.");setLoading(false);return}setLoading(true);setMessage("");try{const r:any=await api.admin.users(token,{search,limit:100,page:1});setRows(Array.isArray(r?.users)?r.users:[]);setTotal(Number(r?.total||0))}catch(e){setMessage(e instanceof Error?e.message:"Unable to load users.")}finally{setLoading(false)}}
 useEffect(()=>{load("")},[]);
 const amountNumber=Number(amount);const valid=selected&&Number.isFinite(amountNumber)&&amountNumber>0&&amountNumber<=100000000&&reason.trim().length>0;
 async function submit(e:FormEvent){e.preventDefault();if(!selected||!valid||busy)return;const verb=action==="credit"?"add":"remove";if(!window.confirm(`Confirm: ${verb} ${money(amountNumber)} ${action==="credit"?"to":"from"} ${selected.email||selected.name||`user #${selected.id}`}?`))return;const token=getSessionToken();if(!token)return;setBusy(true);setMessage("");try{const r:any=await api.admin.adjustWallet(token,{user_id:Number(selected.id),action,amount_ngn:amountNumber,reason:reason.trim(),reference:newRequestKey("admin-wallet")});setRows(prev=>prev.map(u=>String(u.id)===String(selected.id)?{...u,balance_ngn:r?.balance_ngn??u.balance_ngn}:u));setSelected(s=>s?{...s,balance_ngn:r?.balance_ngn??s.balance_ngn}:s);setMessage(`${action==="credit"?"Added":"Removed"} ${money(amountNumber)} successfully. New balance: ${money(r?.balance_ngn)}.`);setAmount("");setReason("")}catch(e){setMessage(e instanceof Error?e.message:"Wallet adjustment failed.")}finally{setBusy(false)}}
 const activeCount=useMemo(()=>rows.filter(u=>u.last_seen_at&&Date.now()-new Date(u.last_seen_at).getTime()<86400000).length,[rows]);
 return <main className="ws-admin-users-page"><section className="ws-admin-users-shell"><header className="ws-admin-users-head"><Link href="/admin/menu" aria-label="Back">‹</Link><div><h1>Users</h1><p>View customers and manage wallet balances</p></div></header>
  <section className="ws-admin-user-stats"><article><strong>{total.toLocaleString()}</strong><span>Total users</span></article><article><strong>{activeCount}</strong><span>Seen in 24h</span></article><article><strong>{money(rows.reduce((s,u)=>s+Number(u.balance_ngn||0),0))}</strong><span>Loaded wallet balance</span></article></section>
  <form className="ws-admin-user-search" onSubmit={e=>{e.preventDefault();load(query)}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search email, name, user ID or Telegram ID"/><button disabled={loading}>{loading?"Loading…":"Search"}</button></form>
  {message&&<div className="ws-admin-user-message" role="status">{message}</div>}
  <section className="ws-admin-user-list">{rows.map(u=><button className="ws-admin-user-row" key={String(u.id)} onClick={()=>{setSelected(u);setMessage("")}}><span className="ws-admin-user-avatar">{String(u.name||u.email||"U").trim().charAt(0).toUpperCase()}</span><span className="ws-admin-user-copy"><strong>{u.name||"WickSpend User"}</strong><small>{u.email||`User #${u.id}`}</small><em>Joined {when(u.created_at)} · Last seen {when(u.last_seen_at)}</em></span><span className="ws-admin-user-balance"><strong>{money(u.balance_ngn)}</strong><small>{Number(u.transaction_count||0)} tx</small><b>Manage ›</b></span></button>)}{!loading&&!rows.length&&<div className="ws-admin-user-empty">No users found.</div>}</section>
  {selected&&<div className="ws-admin-adjust-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setSelected(null)}}><form className="ws-admin-adjust-sheet" onSubmit={submit}><div className="ws-admin-adjust-title"><div><small>USER #{selected.id}</small><h2>{selected.name||selected.email||"WickSpend User"}</h2><p>{selected.email||"No email"}</p></div><button type="button" onClick={()=>setSelected(null)} disabled={busy}>×</button></div><section className="ws-admin-adjust-balance"><span>Current balance</span><strong>{money(selected.balance_ngn)}</strong></section><div className="ws-admin-adjust-tabs"><button type="button" className={action==="credit"?"active":""} onClick={()=>setAction("credit")}>+ Add money</button><button type="button" className={action==="debit"?"active danger":""} onClick={()=>setAction("debit")}>− Remove money</button></div><label><span>Amount (NGN)</span><input type="number" min="1" max="100000000" step="1" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="5000"/></label><label><span>Reason</span><textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why are you changing this balance?"/></label>{action==="debit"&&amountNumber>Number(selected.balance_ngn||0)&&amount!==""&&<div className="ws-admin-adjust-warning">You cannot remove more than the user’s current balance.</div>}<button className={`ws-admin-adjust-submit ${action==="debit"?"danger":""}`} disabled={!valid||busy||(action==="debit"&&amountNumber>Number(selected.balance_ngn||0))}>{busy?"Updating wallet…":action==="credit"?`Add ${amount?money(amountNumber):"money"}`:`Remove ${amount?money(amountNumber):"money"}`}</button><p className="ws-admin-adjust-note">Every change is recorded in WickSpend transactions with the admin, reason, and before/after balance.</p></form></div>}
 </section></main>;
}