"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import ResellerNav from "../ResellerNav";
import { ApiError, wickspendApi } from "@/lib/api";
import { getSessionToken } from "@/lib/session";
function money(v:unknown){const n=Number(v);return Number.isFinite(n)?`₦${n.toLocaleString("en-NG",{maximumFractionDigits:2})}`:"₦0"}
function errorText(e:unknown){return e instanceof ApiError?(e.code||e.message):e instanceof Error?e.message:"Request failed."}
function requestKey(){return typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID():`settlement-${Date.now()}-${Math.random()}`}
export default function ResellerFinance(){
 const router=useRouter();
 const[summary,setSummary]=useState<any>({}),[settlements,setSettlements]=useState<any>({items:[]}),[deposits,setDeposits]=useState<any[]>([]),[tx,setTx]=useState<any[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[tab,setTab]=useState<"transactions"|"deposits"|"settlements">("transactions"),[claiming,setClaiming]=useState(false);
 const load=useCallback(async()=>{const token=getSessionToken();if(!token){router.replace("/login");return}setLoading(true);setMessage("");try{const[s,d,t,p]=await Promise.all([wickspendApi<any>("wickspend/backend/reseller/finance/summary",{token}),wickspendApi<any>("wickspend/backend/reseller/finance/deposits?page=1&limit=50",{token}),wickspendApi<any>("wickspend/backend/reseller/finance/transactions?page=1&limit=50",{token}),wickspendApi<any>("wickspend/backend/reseller/settlements",{token})]);setSummary(s);setDeposits(Array.isArray(d?.items)?d.items:[]);setTx(Array.isArray(t?.items)?t.items:[]);setSettlements(p||{items:[]})}catch(e){setMessage(errorText(e))}finally{setLoading(false)}},[router]);
 useEffect(()=>{load()},[load]);
 async function claim(){const available=Number(settlements?.available_earnings_ngn||0);if(!(available>0))return;if(!window.confirm(`Move ${money(available)} of earned reseller profit into your WickSpend wallet?`))return;const token=getSessionToken();if(!token)return;setClaiming(true);setMessage("");try{const r:any=await wickspendApi("wickspend/backend/reseller/settlements/claim",{method:"POST",token,body:JSON.stringify({request_key:requestKey()})});setMessage(`Settlement completed: ${money(r?.amount_ngn)} credited to your WickSpend wallet.`);await load()}catch(e){setMessage(errorText(e))}finally{setClaiming(false)}}
 const payoutItems=Array.isArray(settlements?.items)?settlements.items:[];
 return <main className="resellerShell"><ResellerNav/><header className="resellerTopbar"><div><span className="eyebrow">Finance</span><h1>Money movement</h1><p>Customer funding, wallet liability, refunds and reseller profit.</p></div><button className="secondaryButton" onClick={load}>Refresh</button></header>{message&&<div className={`resellerMessage ${message.startsWith("Settlement completed")?"success":"error"}`}>{message}</div>}<section className="resellerStats"><Metric label="Customer wallet liability" value={money(summary.customer_wallet_liability_ngn)}/><Metric label="Successful funding" value={money(summary.successful_funding_ngn)}/><Metric label="Earned profit" value={money(settlements.available_earnings_ngn ?? summary.earned_profit_ngn)}/><Metric label="WickSpend wallet" value={money(settlements.wickspend_wallet_balance_ngn)}/></section><section className="resellerGrid three"><Metric label="Completed debits" value={money(summary.completed_customer_debits_ngn)}/><Metric label="Refund credits" value={money(summary.refund_credits_ngn)}/><Metric label="Pending funding" value={money(summary.pending_funding_ngn)}/></section><section className="resellerCard settlementCard"><div><span className="eyebrow">Profit settlement</span><h2>{money(settlements.available_earnings_ngn)} available</h2><p className="subtle">Move earned reseller profit into your existing WickSpend wallet. Only profit already marked earned is eligible; reversed profit is excluded.</p></div><div className="settlementAction"><div><span>Previously settled</span><b>{money(settlements.settled_earnings_ngn)}</b></div><button className="primaryButton" disabled={claiming||Number(settlements.available_earnings_ngn||0)<=0} onClick={claim}>{claiming?"Settling…":"Settle to WickSpend wallet"}</button></div></section><section className="resellerCard"><div className="tabRow"><button className={tab==="transactions"?"active":""} onClick={()=>setTab("transactions")}>Transactions</button><button className={tab==="deposits"?"active":""} onClick={()=>setTab("deposits")}>Deposits</button><button className={tab==="settlements"?"active":""} onClick={()=>setTab("settlements")}>Settlements</button></div>{loading?<div className="emptyState">Loading finance data…</div>:tab==="transactions"?<Transactions items={tx}/>:tab==="deposits"?<Deposits items={deposits}/>:<SettlementHistory items={payoutItems}/>}</section></main>
}
function Metric({label,value}:{label:string;value:string}){return <article className="metricCard"><span>{label}</span><strong>{value}</strong></article>}
function Transactions({items}:{items:any[]}){return items.length?<div className="tableWrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Type</th><th>Purpose</th><th>Amount</th><th>Status</th></tr></thead><tbody>{items.map((x:any)=><tr key={`${x.reference}-${x.created_at}`}><td><b>{x.reference}</b><small>{new Date(x.created_at).toLocaleString()}</small></td><td>{x.customer?.full_name||x.customer?.email||"Customer"}</td><td>{x.type}</td><td>{x.purpose||"—"}</td><td>{money(x.amount_ngn)}</td><td><span className="status muted">{x.status}</span></td></tr>)}</tbody></table></div>:<div className="emptyState">No customer wallet transactions yet.</div>}
function Deposits({items}:{items:any[]}){return items.length?<div className="tableWrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Amount</th><th>Status</th><th>Credited</th><th>Date</th></tr></thead><tbody>{items.map((x:any)=><tr key={x.reference}><td><b>{x.reference}</b></td><td>{x.customer?.full_name||x.customer?.email||"Customer"}</td><td>{money(x.amount_ngn)}</td><td><span className="status muted">{x.status}</span></td><td>{x.credited?"Yes":"No"}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="emptyState">No customer deposits yet.</div>}
function SettlementHistory({items}:{items:any[]}){return items.length?<div className="tableWrap"><table><thead><tr><th>Reference</th><th>Amount</th><th>Destination</th><th>Balance after</th><th>Status</th><th>Date</th></tr></thead><tbody>{items.map((x:any)=><tr key={x.reference}><td><b>{x.reference}</b></td><td>{money(x.amount_ngn)}</td><td>WickSpend wallet</td><td>{money(x.balance_after_ngn)}</td><td><span className={`status ${x.status==="completed"?"good":"warn"}`}>{x.status}</span></td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="emptyState">No profit settlements yet.</div>}
