"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import styles from "../rentals.module.css";
import { rentalExpiry, rentalMessages, remainingLabel, StoreRental, storeRentalRequest } from "@/lib/store-rentals";

export default function StoreRentalDetailPage(){
  const params=useParams<{slug:string;rentalId:string}>(),slug=String(params.slug||"").toLowerCase(),reference=decodeURIComponent(String(params.rentalId||"")),router=useRouter();
  const[rental,setRental]=useState<StoreRental|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[message,setMessage]=useState(""),[now,setNow]=useState(Date.now());
  const load=useCallback(async(manual=false)=>{manual?setRefreshing(true):setLoading(true);setMessage("");try{const result:any=await storeRentalRequest(slug,`rentals/status?reference=${encodeURIComponent(reference)}`);setRental(result.rental||result.order||result)}catch(error){setMessage(error instanceof Error?error.message:"Unable to refresh this rental.")}finally{setLoading(false);setRefreshing(false)}},[slug,reference]);
  useEffect(()=>{load()},[load]);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  const messages=rentalMessages(rental),expires=rentalExpiry(rental),expired=remainingLabel(expires,now)==="Expired";
  return <main className={styles.page}><div className={styles.shell}><header className={styles.topbar}><button className={styles.back} onClick={()=>router.push(`/store/${slug}/rentals`)} aria-label="Back">‹</button><div><h1>Rental Details</h1><p>Number and SMS messages</p></div><button className={styles.ghost} disabled={refreshing} onClick={()=>load(true)}>{refreshing?"Checking…":"Refresh"}</button></header><div className={styles.navLinks}><Link href={`/store/${slug}/rent-number`}>Rent Number</Link><Link href={`/store/${slug}/rentals`}>My Rentals</Link></div>{message&&<div className={`${styles.notice} ${styles.error}`}>{message}</div>}{loading?<><div className={styles.skeleton}/><div className={styles.skeleton}/></>:rental?<><section className={`${styles.panel} ${styles.detailHero}`}><span className={`${styles.status} ${expired?styles.ended:""}`}>{expired?"Expired":rental.status||"Active"}</span><div className={styles.number}>{rental.phone_number||"Number processing"}</div><div className={styles.metaLine}>{rental.service_name||rental.service_code} · {rental.country_name||rental.country_code}</div><div className={styles.countdown}>{remainingLabel(expires,now)}</div><div className={styles.metaLine}>{expires?`Expires ${new Date(expires).toLocaleString()}`:"Expiry unavailable"}</div><div className={styles.actions} style={{marginTop:16}}><button className={styles.primary} onClick={()=>navigator.clipboard?.writeText(String(rental.phone_number||""))}>Copy Number</button><button className={styles.ghost} disabled={refreshing||expired} onClick={()=>load(true)}>{refreshing?"Checking SMS…":"Refresh SMS"}</button></div></section><div className={styles.sectionHead}><h2>SMS Messages</h2><small>{messages.length} received</small></div>{messages.length?<div className={styles.messages}>{messages.map((sms:any,index:number)=>{const otp=sms.code||sms.otp||"";return <article className={styles.messageCard} key={sms.id||`${sms.created_at||sms.time||"sms"}-${index}`}><div className={styles.messageHead}><b>{sms.sender||sms.from||"SMS"}</b><span>{sms.created_at||sms.received_at||sms.time?new Date(sms.created_at||sms.received_at||sms.time).toLocaleString():"Just now"}</span></div><p className={styles.messageBody}>{sms.message||sms.text||sms.body||String(sms)}</p>{otp&&<button className={styles.otp} onClick={()=>navigator.clipboard?.writeText(String(otp))}>{otp}</button>}</article>})}</div>:<div className={styles.empty}>{expired?"This rental expired without a stored SMS message.":"No SMS received yet. Tap Refresh SMS to check again."}</div>}</>:<div className={styles.empty}>Rental not found.</div>}</div></main>
}
