"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { api } from "@/lib/api";
import { canonicalSessionTokenFromResponse, clearSessionTokenIfMatches, getSessionToken, saveSessionToken } from "@/lib/session";
import styles from "../../login/login.module.css";

const validEmail=(value:string)=>/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value.trim());

export default function StaffLoginPage(){
  const [email,setEmail]=useState(""),[code,setCode]=useState(""),[step,setStep]=useState<"email"|"code">("email"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const mounted=useRef(true);
  useEffect(()=>{mounted.current=true;const token=getSessionToken();if(token){api.staff.marketplaceAccess(token).then((r:any)=>{if(r?.authorized===true&&mounted.current)window.location.replace("/staff/marketplace")}).catch(()=>{})}return()=>{mounted.current=false}},[]);

  async function requestCode(e?:FormEvent){e?.preventDefault();if(busy)return;const mail=email.trim().toLowerCase();if(!validEmail(mail))return setMessage("Enter a valid staff email address.");setBusy(true);setMessage("");try{await api.auth.emailStart({email:mail});if(!mounted.current)return;setEmail(mail);setCode("");setStep("code");setMessage("A secure 6-digit sign-in code was sent to your email.")}catch(error){if(mounted.current)setMessage(error instanceof Error?error.message:"Unable to send verification code.")}finally{if(mounted.current)setBusy(false)}}

  async function verify(e:FormEvent){e.preventDefault();if(busy)return;const mail=email.trim().toLowerCase();if(!validEmail(mail)||!/^\d{6}$/.test(code))return setMessage("Enter the complete 6-digit verification code.");setBusy(true);setMessage("");try{const response:any=await api.auth.emailVerify({email:mail,code});const token=String(canonicalSessionTokenFromResponse(response)||"");if(!token)throw new Error("Unable to create a secure staff session.");saveSessionToken(token);try{const access:any=await api.staff.marketplaceAccess(token);if(access?.authorized!==true)throw new Error("This account does not have Marketplace staff access.");window.location.replace("/staff/marketplace")}catch(error){try{await api.auth.logout(token)}catch{}clearSessionTokenIfMatches(token);throw error}}catch(error){if(mounted.current)setMessage(error instanceof Error?error.message:"Staff verification failed.")}finally{if(mounted.current)setBusy(false)}}
  if(step==="code") return <main className={styles.screen}><p className={styles.brand}>WickSpend Staff</p><section className={styles.content} aria-busy={busy}><h1 className={styles.title}>Verify staff access</h1><p className={styles.lead}>Enter the verification code sent to {email}.</p><form className={styles.form} onSubmit={verify}><label className={styles.label} htmlFor="staff-code">6-digit code</label><input id="staff-code" className={styles.field} type="text" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>{setCode(e.target.value.replace(/\D/g,"").slice(0,6));setMessage("")}} placeholder="Enter 6-digit code" disabled={busy}/><button className={styles.primary} type="submit" disabled={busy||code.length!==6}>{busy?"Verifying…":"Verify & Continue"}</button><button className={styles.helperButton} type="button" disabled={busy} onClick={()=>void requestCode()}>Send new code</button><button className={styles.helperButton} type="button" disabled={busy} onClick={()=>{setStep("email");setCode("");setMessage("")}}>Change email</button></form>{message&&<p className={styles.message} role="status">{message}</p>}<p className={styles.secure}>Marketplace-only staff access.</p></section></main>;

  return <main className={styles.screen}><p className={styles.brand}>WickSpend Staff</p><section className={styles.content} aria-busy={busy}><h1 className={styles.title}>Marketplace Assistant</h1><p className={styles.lead}>Sign in with the email assigned by the WickSpend owner.</p><form className={styles.form} onSubmit={requestCode}><label className={styles.label} htmlFor="staff-email">Staff email address</label><input id="staff-email" className={styles.field} type="email" inputMode="email" autoComplete="email" value={email} onChange={e=>{setEmail(e.target.value);setMessage("")}} placeholder="Enter staff email" disabled={busy}/><button className={styles.primary} type="submit" disabled={busy||!email.trim()}>{busy?"Sending…":"Send Secure Code"}</button></form>{message&&<p className={styles.message} role="status">{message}</p>}<p className={styles.secure}>This login does not grant access to the main WickSpend Admin.</p></section></main>;
}
