"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {BottomNav} from "@/components/BottomNav";
import {api} from "@/lib/api";
import {getSessionToken} from "@/lib/session";
import s from "../../temp-mail.module.css";

const payloadOf=(x:any)=>x?.order||x?.data?.order||x?.data||x;
const emailOf=(x:any)=>String(x?.email||x?.address||x?.email_address||x?.mail||x?.mailbox||x?.mailbox_address||x?.inbox_address||x?.data?.email||x?.data?.address||x?.data?.email_address||"");
const senderOf=(m:any)=>String(m?.sender||m?.from||m?.service||m?.source||"Message");
const subjectOf=(m:any)=>String(m?.subject||m?.title||"Verification email");
const bodyOf=(m:any)=>String(m?.text||m?.message||m?.body||m?.content||"");
const receivedAt=(m:any)=>{const raw=m?.received_at||m?.created_at||m?.createdAt||m?.date||m?.timestamp;if(!raw)return "Received";const d=new Date(raw);return Number.isNaN(d.getTime())?String(raw):d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})};
const ngn=(v:any)=>Number.isFinite(Number(v))?`₦${Number(v).toLocaleString("en-NG")}`:"";

export default function TempMailInbox(){
  const params=useParams<{reference:string}>(),router=useRouter(),reference=decodeURIComponent(String(params.reference||""));
  const[order,setOrder]=useState<any>(null),[message,setMessage]=useState("Loading inbox…"),[refreshing,setRefreshing]=useState(false),[cancelling,setCancelling]=useState(false);
  const load=useCallback(async(silent=false)=>{const token=getSessionToken();if(!token){setMessage("Please sign in to open this inbox.");return}if(!silent)setRefreshing(true);try{const d:any=await api.tempMail.status(token,reference);const next=payloadOf(d);setOrder(next);sessionStorage.setItem(`wickspend.tempMailOrder.${reference}`,JSON.stringify(next));if(!silent)setMessage(emailOf(next)?"":"Preparing your email address…")}catch(e){if(!silent)setMessage(e instanceof Error?e.message:"Unable to refresh inbox")}finally{if(!silent)setRefreshing(false)}},[reference]);
  useEffect(()=>{let cached:any=null;try{const raw=sessionStorage.getItem(`wickspend.tempMailOrder.${reference}`);if(raw)cached=JSON.parse(raw)}catch{}if(cached)setOrder(cached);load();},[load,reference]);
  const status=String(order?.status||"Active"),refunded=order?.refunded===true,terminal=/expired|complete|cancel|refunded|closed|failed/i.test(status)||refunded;
  const otp=String(order?.otp_code||order?.otp||order?.code||order?.verification_code||"").trim();
  const canCancel=!terminal&&!otp&&Boolean(order?.provider_mail_id)&&/active|waiting/i.test(status);
  useEffect(()=>{if(terminal)return;const interval=emailOf(order)?8000:2500;const id=window.setInterval(()=>load(true),interval);return()=>window.clearInterval(id)},[terminal,load,order]);
  const email=emailOf(order);const expiry=String(order?.expires_in||order?.expires_at||order?.remaining||order?.ttl||"");
  const mails=useMemo(()=>{const raw=order?.messages||order?.emails||order?.inbox||[];return Array.isArray(raw)?raw:raw?[raw]:[]},[order]);
  async function copy(){if(!email)return;try{await navigator.clipboard.writeText(email);setMessage("Email copied.")}catch{setMessage("Unable to copy email.")}}
  async function cancelMailbox(){if(cancelling||!canCancel)return;if(!window.confirm("Cancel this Temp Mail? A refund is only issued if the provider confirms the cancellation."))return;const token=getSessionToken();if(!token){setMessage("Please sign in before cancelling this mailbox.");return}setCancelling(true);setMessage("");try{const result:any=await api.tempMail.cancel(token,reference);const next=payloadOf(result);const confirmed=next?.refunded===true||/cancelled|refunded/i.test(String(next?.status||""));if(!confirmed){setMessage("Cancellation was not confirmed. Your mailbox has not been marked as refunded.");await load(true);return}const merged={...order,...next,status:next?.status||"cancelled",refunded:true};setOrder(merged);sessionStorage.setItem(`wickspend.tempMailOrder.${reference}`,JSON.stringify(merged));const amount=next?.refund_amount_ngn??next?.amount_ngn;setMessage(amount?`Mailbox cancelled. ${ngn(amount)} was refunded to your wallet.`:"Mailbox cancelled and refunded to your WickSpend wallet.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to cancel this mailbox");await load(true)}finally{setCancelling(false)}}
  return <main className={s.page}><div className={s.topbar}><button className={s.back} onClick={()=>router.push("/temp-mail")} aria-label="Back">‹</button><div><h1>Temp Mail Inbox</h1><div className={s.step}>{terminal?refunded?"Cancelled and refunded":"Mailbox closed":email?"Checking for new mail":"Preparing mailbox"}</div></div><span/></div><section className={s.panel}><div className={s.inboxHead}><div><div className={s.emailTop}>{email||"Preparing email address…"}</div><div className={s.muted}>{expiry?`Expires: ${expiry}`:"Temporary mailbox"}</div></div><span className={`${s.statusPill} ${terminal?s.expired:""}`}>{refunded?"Refunded":terminal?status:status}</span></div><div className={s.inlineActions} style={{marginTop:14}}><button onClick={copy} disabled={!email}>Copy email</button><button onClick={()=>load()} disabled={refreshing||terminal}>{refreshing?"Refreshing…":"Refresh inbox"}</button></div>{canCancel&&<button className={s.cancelButton} type="button" onClick={cancelMailbox} disabled={cancelling}>{cancelling?"Cancelling…":"Cancel & Refund"}</button>}{refunded&&<div className={s.refundNotice}>This Temp Mail was cancelled and its eligible amount was returned to your WickSpend wallet.</div>}</section><section className={s.panel} style={{marginTop:14}}><div className={s.sectionHead}><div><h2>Inbox</h2><p>{mails.length?`${mails.length} message${mails.length===1?"":"s"}`:"Incoming messages appear here."}</p></div></div>{mails.length?<div className={s.messageList}>{mails.map((m:any,i:number)=><Link key={m?.id||i} href={`/temp-mail/inbox/${encodeURIComponent(reference)}/message/${i}`} className={s.messageCard} style={{textDecoration:"none"}}><b>{senderOf(m)}</b><small>{subjectOf(m)} · {receivedAt(m)}</small><p>{bodyOf(m)||"Open message"}</p></Link>)}</div>:<div className={s.waiting}>{terminal?<div><h3>{refunded?"Mailbox cancelled":"No new messages"}</h3><p>{refunded?"Polling has stopped because this mailbox was cancelled and refunded.":"This mailbox is no longer active, so WickSpend has stopped polling it."}</p></div>:<div><div className={s.waitingPulse}/><h3>{email?"Waiting for messages…":"Preparing your mailbox…"}</h3><p>{email?"WickSpend is checking this inbox without reloading the full page.":"The email address will appear automatically as soon as it is ready."}</p></div>}</div>}</section>{message&&<p className={s.screenMessage} role="status">{message}</p>}<BottomNav/></main>
}
