"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {api} from "@/lib/api";
import {clearSessionToken,getSessionToken,saveSessionToken} from "@/lib/session";
import styles from "./login.module.css";

const digitsOnly=(value:string)=>/^\d+$/.test(value);

export default function Login(){
  const router=useRouter(),[telegramId,setTelegramId]=useState(""),[code,setCode]=useState(""),[step,setStep]=useState<"request"|"verify">("request"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),actionSeq=useRef(0),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;let active=true;const t=getSessionToken();if(t)api.auth.session(t).then(()=>{if(active&&mounted.current)router.replace("/")}).catch(()=>{if(active&&mounted.current){clearSessionToken();setMessage("")}});return()=>{active=false;mounted.current=false;actionSeq.current++}},[router]);
  async function requestCode(e:FormEvent){e.preventDefault();if(busy)return;const id=telegramId.trim();if(!id)return setMessage("Enter your Telegram user ID.");if(!digitsOnly(id))return setMessage("Telegram user ID must contain numbers only.");const seq=++actionSeq.current;setBusy(true);setMessage("Sending verification code…");try{await api.auth.telegramStart({telegram_user_id:id});if(!mounted.current||seq!==actionSeq.current)return;setTelegramId(id);setCode("");setStep("verify");setMessage("Verification code sent. Enter the code to continue.")}catch(e){if(mounted.current&&seq===actionSeq.current)setMessage(e instanceof Error?e.message:"Unable to send verification code")}finally{if(mounted.current&&seq===actionSeq.current)setBusy(false)}}
  async function verify(e:FormEvent){e.preventDefault();if(busy)return;const id=telegramId.trim(),otp=code.trim();if(!id){setStep("request");return setMessage("Enter your Telegram user ID again.")}if(!digitsOnly(id)){setStep("request");return setMessage("Telegram user ID must contain numbers only.")}if(!otp)return setMessage("Enter the verification code.");if(!digitsOnly(otp))return setMessage("Verification code must contain numbers only.");const seq=++actionSeq.current;setBusy(true);setMessage("Verifying…");try{const r:any=await api.auth.telegramVerify({telegram_user_id:id,code:otp}),t=r?.session_token||r?.token||r?.data?.session_token||r?.data?.token;if(!t)throw new Error("Session token was not returned after verification.");saveSessionToken(String(t));try{await api.auth.session(String(t))}catch(e){clearSessionToken();throw e}if(!mounted.current||seq!==actionSeq.current)return;setMessage("Signed in successfully.");router.replace("/")}catch(e){clearSessionToken();if(mounted.current&&seq===actionSeq.current)setMessage(e instanceof Error?e.message:"Verification failed")}finally{if(mounted.current&&seq===actionSeq.current)setBusy(false)}}
  function changeId(){actionSeq.current++;setBusy(false);setStep("request");setCode("");setMessage("")}
  return <main className={styles.screen}><p className={styles.brand}>WickSpend</p><section className={styles.content} aria-busy={busy}><h1 className={styles.title}>{step==="request"?"Welcome back":"Verify your account"}</h1><p className={`${styles.lead} ${step==="verify"?styles.verifyLead:""}`}>{step==="request"?"Log in securely with your Telegram-linked WickSpend account.":`Enter the verification code sent for Telegram ID ${telegramId}.`}</p>{step==="request"?<form className={styles.form} onSubmit={requestCode}><div className={styles.telegramHint}><span className={styles.telegramIcon} aria-hidden="true">✈</span><span>Telegram secure verification</span></div><label className={styles.label} htmlFor="telegram-id">Telegram user ID</label><input id="telegram-id" className={styles.field} inputMode="numeric" autoComplete="off" value={telegramId} onChange={e=>{setTelegramId(e.target.value);if(message)setMessage("")}} placeholder="Enter your Telegram ID" disabled={busy}/><div className={styles.helperRow}><span>Use the Telegram ID linked to WickSpend.</span></div><button className={styles.primary} type="submit" disabled={busy||!telegramId.trim()}>{busy?"Sending…":"Continue"}</button><button className={styles.secondary} type="button" onClick={()=>router.push("/")}>Back to WickSpend</button></form>:<form className={styles.form} onSubmit={verify}><label className={styles.label} htmlFor="verification-code">Verification code</label><input id="verification-code" className={`${styles.field} ${styles.otp}`} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>{setCode(e.target.value);if(message)setMessage("")}} placeholder="000000" disabled={busy}/><div className={styles.helperRow}><span>Enter the code you received.</span><button className={styles.helperButton} type="button" disabled={busy} onClick={changeId}>Change Telegram ID</button></div><button className={styles.primary} type="submit" disabled={busy||!code.trim()}>{busy?"Verifying…":"Verify & Sign In"}</button><button className={styles.secondary} type="button" disabled={busy} onClick={changeId}>Start Again</button></form>}{message&&<p className={styles.message} role="status">{message}</p>}<p className={styles.secure}>Secure access to your wallet, purchases and WickSpend services.</p></section></main>}
