"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {api,googleAuthStartUrl} from "@/lib/api";
import {clearSessionToken,getSessionToken,saveSessionToken} from "@/lib/session";
import styles from "./login.module.css";

const digitsOnly=(value:string)=>/^\d+$/.test(value);
const GoogleIcon=()=> <svg className={styles.providerIcon} viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.4-.18-2.07H12v3.92h5.38a4.6 4.6 0 0 1-2 3.02v2.51h3.24c1.9-1.75 2.98-4.33 2.98-7.38Z"/><path fill="#34A853" d="M12 22c2.7 0 4.96-.9 6.62-2.39l-3.24-2.51c-.9.6-2.04.96-3.38.96-2.6 0-4.8-1.75-5.6-4.1H3.05v2.58A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.4 13.96A6 6 0 0 1 6.08 12c0-.68.12-1.34.32-1.96V7.46H3.05A10 10 0 0 0 2 12c0 1.62.39 3.16 1.05 4.54l3.35-2.58Z"/><path fill="#EA4335" d="M12 5.94c1.47 0 2.8.5 3.84 1.5l2.88-2.88C16.96 2.92 14.7 2 12 2a10 10 0 0 0-8.95 5.46l3.35 2.58c.8-2.35 3-4.1 5.6-4.1Z"/></svg>;

export default function Login(){
  const router=useRouter(),[telegramId,setTelegramId]=useState(""),[code,setCode]=useState(""),[step,setStep]=useState<"request"|"verify">("request"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),actionSeq=useRef(0),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;let active=true;const url=new URL(window.location.href),handoff=url.searchParams.get("google_handoff"),googleError=url.searchParams.get("google_error");if(googleError){setMessage(googleError==="cancelled"?"Google sign-in was cancelled.":"Google sign-in could not be completed. Please try again.");window.history.replaceState({},"","/login");}if(handoff){setBusy(true);setMessage("Completing Google sign-in…");api.auth.googleExchange(handoff).then((r:any)=>{const t=r?.session_token||r?.token||r?.data?.session_token||r?.data?.token;if(!t)throw new Error("Session token was not returned after Google sign-in.");saveSessionToken(String(t));return api.auth.session(String(t)).then(()=>t)}).then(()=>{if(active&&mounted.current){window.history.replaceState({},"","/login");router.replace("/")}}).catch(e=>{clearSessionToken();if(active&&mounted.current){setMessage(e instanceof Error?e.message:"Google sign-in failed");window.history.replaceState({},"","/login")}}).finally(()=>{if(active&&mounted.current)setBusy(false)});return()=>{active=false;mounted.current=false;actionSeq.current++}}const t=getSessionToken();if(t)api.auth.session(t).then(()=>{if(active&&mounted.current)router.replace("/")}).catch(()=>{if(active&&mounted.current){clearSessionToken();setMessage("")}});return()=>{active=false;mounted.current=false;actionSeq.current++}},[router]);
  async function requestCode(e:FormEvent){e.preventDefault();if(busy)return;const id=telegramId.trim();if(!id)return setMessage("Enter your Telegram user ID.");if(!digitsOnly(id))return setMessage("Telegram user ID must contain numbers only.");const seq=++actionSeq.current;setBusy(true);setMessage("Sending verification code…");try{await api.auth.telegramStart({telegram_user_id:id});if(!mounted.current||seq!==actionSeq.current)return;setTelegramId(id);setCode("");setStep("verify");setMessage("Verification code sent. Enter the code to continue.")}catch(e){if(mounted.current&&seq===actionSeq.current)setMessage(e instanceof Error?e.message:"Unable to send verification code")}finally{if(mounted.current&&seq===actionSeq.current)setBusy(false)}}
  async function verify(e:FormEvent){e.preventDefault();if(busy)return;const id=telegramId.trim(),otp=code.trim();if(!id){setStep("request");return setMessage("Enter your Telegram user ID again.")}if(!digitsOnly(id)){setStep("request");return setMessage("Telegram user ID must contain numbers only.")}if(!otp)return setMessage("Enter the verification code.");if(!digitsOnly(otp))return setMessage("Verification code must contain numbers only.");const seq=++actionSeq.current;setBusy(true);setMessage("Verifying…");try{const r:any=await api.auth.telegramVerify({telegram_user_id:id,code:otp}),t=r?.session_token||r?.token||r?.data?.session_token||r?.data?.token;if(!t)throw new Error("Session token was not returned after verification.");saveSessionToken(String(t));try{await api.auth.session(String(t))}catch(e){clearSessionToken();throw e}if(!mounted.current||seq!==actionSeq.current)return;setMessage("Signed in successfully.");router.replace("/")}catch(e){clearSessionToken();if(mounted.current&&seq===actionSeq.current)setMessage(e instanceof Error?e.message:"Verification failed")}finally{if(mounted.current&&seq===actionSeq.current)setBusy(false)}}
  function changeId(){actionSeq.current++;setBusy(false);setStep("request");setCode("");setMessage("")}
  function continueGoogle(){if(busy)return;setBusy(true);setMessage("Opening Google sign-in…");window.location.assign(googleAuthStartUrl())}
  return <main className={styles.screen}><p className={styles.brand}>WickSpend</p><section className={styles.content} aria-busy={busy}><h1 className={styles.title}>{step==="request"?"Welcome back":"Verify your account"}</h1><p className={`${styles.lead} ${step==="verify"?styles.verifyLead:""}`}>{step==="request"?"Log in securely with your WickSpend account.":`Enter the verification code sent for Telegram ID ${telegramId}.`}</p>{step==="request"?<><form className={styles.form} onSubmit={requestCode}><div className={styles.telegramHint}><span className={styles.telegramIcon} aria-hidden="true">✈</span><span>Telegram secure verification</span></div><label className={styles.label} htmlFor="telegram-id">Telegram user ID</label><input id="telegram-id" className={styles.field} inputMode="numeric" autoComplete="off" value={telegramId} onChange={e=>{setTelegramId(e.target.value);if(message)setMessage("")}} placeholder="Enter your Telegram ID" disabled={busy}/><div className={styles.helperRow}><span>Use the Telegram ID linked to WickSpend.</span></div><button className={styles.primary} type="submit" disabled={busy||!telegramId.trim()}>{busy?"Sending…":"Continue with Telegram"}</button></form><div className={styles.divider}>or</div><button className={styles.providerButton} type="button" disabled={busy} onClick={continueGoogle}><GoogleIcon/>Continue with Google</button><button className={styles.secondary} type="button" onClick={()=>router.push("/")}>Back to WickSpend</button></>:<form className={styles.form} onSubmit={verify}><label className={styles.label} htmlFor="verification-code">Verification code</label><input id="verification-code" className={`${styles.field} ${styles.otp}`} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>{setCode(e.target.value);if(message)setMessage("")}} placeholder="000000" disabled={busy}/><div className={styles.helperRow}><span>Enter the code you received.</span><button className={styles.helperButton} type="button" disabled={busy} onClick={changeId}>Change Telegram ID</button></div><button className={styles.primary} type="submit" disabled={busy||!code.trim()}>{busy?"Verifying…":"Verify & Sign In"}</button><button className={styles.secondary} type="button" disabled={busy} onClick={changeId}>Start Again</button></form>}{message&&<p className={styles.message} role="status">{message}</p>}<p className={styles.secure}>Secure access to your wallet, purchases and WickSpend services.</p></section></main>}
