"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {BottomNav} from "@/components/BottomNav";
import {api} from "@/lib/api";
import {getSessionToken} from "@/lib/session";

const refOf=(o:any)=>String(o?.reference||o?.order_reference||o?.transaction_reference||o?.ref||o?.id||"");
const statusOf=(o:any)=>String(o?.status||o?.order_status||o?.state||"").toLowerCase();
const money=(v:any)=>{const n=Number(v);return Number.isFinite(n)?`₦${n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`:"—"};

export default function CheckoutCompleted(){
  const[order,setOrder]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{const q=new URLSearchParams(window.location.search);const reference=q.get("reference")||q.get("ref")||"";const token=getSessionToken();if(!reference){setError("Order reference is missing.");setLoading(false);return}if(!token){setError("Please sign in to view this purchase.");setLoading(false);return}api.orders.list(token).then((r:any)=>{const list=Array.isArray(r)?r:(r?.orders||r?.items||r?.data||[]);const found=Array.isArray(list)?list.find((x:any)=>refOf(x)===reference):null;if(!found){setError("We could not confirm this purchase from your order history.");return}const s=statusOf(found);if(!/success|successful|paid|completed|delivered|active/.test(s)){setError("This order is not confirmed as completed yet.");return}setOrder(found)}).catch((e:any)=>setError(e instanceof Error?e.message:"Unable to load order")).finally(()=>setLoading(false));},[]);
  const reference=order?refOf(order):"";
  const service=order?.service_name||order?.service||order?.product_name||order?.product||"Number order";
  const country=order?.country_name||order?.country||"";
  const amount=order?.final_amount_ngn??order?.amount_ngn??order?.total_ngn??order?.amount;
  const product=useMemo(()=>country?`${country} ${service}`:service,[country,service]);
  return <main className="shell appShell"><div className="cc">{loading?<section className="state"><div className="circle">•••</div><h1>Checking purchase</h1><p>Confirming your order from WickSpend.</p></section>:error?<section className="state"><div className="circle">!</div><h1>Purchase not confirmed</h1><p>{error}</p><Link className="primary" href="/orders">Check Orders</Link><Link className="secondary" href="/">Back to Home</Link></section>:<><section className="state"><div className="circle">✓</div><h1>Purchase complete</h1><p>Your order was placed successfully.</p></section><section className="order"><small>ORDER</small><h2>{product}</h2>{country&&<p>{country} • {service}</p>}<div className="row"><span>Order ID</span><strong>#{reference}</strong></div><div className="row"><span>Paid</span><strong>{money(amount)}</strong></div></section><Link className="primary" href={`/orders?reference=${encodeURIComponent(reference)}`}>View order details</Link><Link className="secondary" href="/">Back to Home</Link><section className="receipt"><b>Receipt saved</b><p>You can reopen this purchase anytime from Orders.</p></section></>}</div><BottomNav/><style>{`body{background:#fbfbfb}.cc{padding:70px 18px 110px;max-width:430px;margin:auto}.state{text-align:center}.circle{width:88px;height:88px;border-radius:50%;background:#050505;color:#fff;display:grid;place-items:center;margin:0 auto 32px;font-size:32px;font-weight:700}.state h1{font-size:26px;margin:0 0 8px}.state p{font-size:11px;color:#6b6b73;margin:0 auto 40px;max-width:290px}.order{background:#fff;border:1px solid #e0e0e5;border-radius:24px;padding:20px 18px;margin:0 0 48px}.order small{font-size:9px;color:#6b6b73;font-weight:600}.order h2{font-size:16px;margin:14px 0 8px}.order p{font-size:10px;color:#6b6b73;margin:0}.row{display:flex;justify-content:space-between;gap:20px;margin-top:30px;font-size:10px;color:#6b6b73}.row strong{font-size:11px;color:#050505;text-align:right;max-width:60%;overflow-wrap:anywhere}.primary,.secondary{height:58px;border-radius:29px;display:flex;align-items:center;justify-content:center;text-decoration:none;font-size:13px;font-weight:600}.primary{background:#050505;color:#fff;margin-bottom:14px}.secondary{height:50px;background:#fff;color:#050505;border:1px solid #e0e0e5;margin-bottom:18px}.receipt{background:#f6f7f9;border:1px solid #e0e0e5;border-radius:20px;padding:18px}.receipt b{font-size:11px}.receipt p{font-size:10px;color:#6b6b73;margin:12px 0 0;line-height:1.5}.state .primary{margin-top:18px}.state .secondary{margin-top:0}@media(min-width:700px){.cc{padding-top:96px}}`}</style></main>;
}
