"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import ResellerNav from "../ResellerNav";
import { ApiError, wickspendApi } from "@/lib/api";
import { getSessionToken } from "@/lib/session";

function err(error:unknown){return error instanceof ApiError ? (error.code || error.message) : error instanceof Error ? error.message : "Request failed."}
function normalizeDomain(value:string){return value.trim().toLowerCase().replace(/^https?:\/\//,"").split("/")[0].replace(/\.$/,"")}
function expectedDomainWait(error:unknown){return error instanceof ApiError&&["DNS_RECORD_NOT_FOUND","DNS_LOOKUP_FAILED","RATE_LIMITED"].includes(String(error.code||""))}

export default function ResellerStore(){
 const router=useRouter();
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[profile,setProfile]=useState<any>(null),[pricing,setPricing]=useState<any[]>([]),[domain,setDomain]=useState<any>(null);
 const[form,setForm]=useState({store_name:"",store_slug:"",logo_url:"",primary_color:"#0866F5",support_email:"",support_phone:"",custom_domain:"",enabled:false,rent_number_enabled:true});
 const[rule,setRule]=useState({product_type:"number",product_code:"*",country_code:"",markup_ngn:"0",fixed_price_ngn:"",enabled:true});
 const[domainInput,setDomainInput]=useState("");
 const cleanStoreUrl=form.store_slug?`https://wickspend.com/store/${form.store_slug}`:"";
 const subscriptionActive=Boolean(profile?.subscription?.active);
 const subscriptionPending=String(profile?.subscription?.status||"").toLowerCase()==="pending";

 const load=useCallback(async()=>{const token=getSessionToken();if(!token){router.replace("/login");return}setLoading(true);setMessage("");try{const[p,pr,d]=await Promise.all([wickspendApi<any>("wickspend/backend/reseller/profile",{token}),wickspendApi<any>("wickspend/backend/reseller/pricing",{token}),wickspendApi<any>("wickspend/backend/reseller/domain/status",{token})]);setProfile(p);setPricing(Array.isArray(pr?.items)?pr.items:[]);setDomain(d);const s=p?.store||{};setForm({store_name:s.store_name||"",store_slug:s.slug||"",logo_url:s.logo_url||"",primary_color:s.primary_color||"#0866F5",support_email:s.support_email||"",support_phone:s.support_phone||"",custom_domain:s.custom_domain||"",enabled:Boolean(s.enabled),rent_number_enabled:s.rent_number_enabled!==false});setDomainInput(d?.domain||s.custom_domain||"")}catch(e){setMessage(err(e))}finally{setLoading(false)}},[router]);
 useEffect(()=>{load()},[load]);

 useEffect(()=>{
  if(!subscriptionActive||!domain?.configured||domain?.activation_ready)return;
  let cancelled=false;
  const poll=async()=>{const token=getSessionToken();if(!token||cancelled)return;try{if(domain?.ownership_status!=="verified"){try{await wickspendApi("wickspend/backend/reseller/domain/verify",{method:"POST",token,body:"{}"})}catch(e){if(!expectedDomainWait(e))throw e}}const latest=await wickspendApi<any>("wickspend/backend/reseller/domain/status",{token});if(cancelled)return;setDomain(latest);if(latest?.domain)setDomainInput(latest.domain);if(latest?.activation_ready)setMessage(`Connected — https://${latest.domain} is live with HTTPS.`);else if(latest?.ownership_status==="verified")setMessage("Domain detected. WickSpend is finishing routing and HTTPS automatically.")}catch(e){if(cancelled||expectedDomainWait(e))return}};
  const first=window.setTimeout(poll,1500);
  const interval=window.setInterval(poll,10000);
  return()=>{cancelled=true;window.clearTimeout(first);window.clearInterval(interval)};
 },[subscriptionActive,domain?.configured,domain?.domain,domain?.ownership_status,domain?.activation_ready]);

 async function saveStore(){const token=getSessionToken();if(!token)return;if(!subscriptionActive){setMessage(subscriptionPending?"Subscription activation is pending. Do not pay again while confirmation is pending.":"Your reseller subscription is inactive. Subscribe or renew to change store settings.");return}setBusy(true);setMessage("");try{await wickspendApi("wickspend/backend/reseller/store",{method:"POST",token,body:JSON.stringify(form)});setMessage("Store settings saved.");await load()}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function saveRule(){const token=getSessionToken();if(!token)return;if(!subscriptionActive){setMessage(subscriptionPending?"Subscription activation is pending. Do not pay again while confirmation is pending.":"Your reseller subscription is inactive. Subscribe or renew to change pricing.");return}setBusy(true);setMessage("");try{await wickspendApi("wickspend/backend/reseller/pricing",{method:"POST",token,body:JSON.stringify({...rule,markup_ngn:Number(rule.markup_ngn||0),fixed_price_ngn:rule.fixed_price_ngn===""?null:Number(rule.fixed_price_ngn)})});setMessage("Pricing rule saved.");await load()}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function requestDomain(){const token=getSessionToken();if(!token)return;if(!subscriptionActive){setMessage(subscriptionPending?"Subscription activation is pending. Do not pay again while confirmation is pending.":"Your reseller subscription is inactive. Subscribe or renew to manage a custom domain.");return}const requested=normalizeDomain(domainInput);setDomainInput(requested);setBusy(true);setMessage("");try{const created=await wickspendApi<any>("wickspend/backend/reseller/domain/request",{method:"POST",token,body:JSON.stringify({domain:requested})});setDomain({...created,configured:true});setMessage("One DNS record left. Add the CNAME below — WickSpend will detect it and finish setup automatically.")}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function verifyDomain(){const token=getSessionToken();if(!token)return;if(!subscriptionActive){setMessage(subscriptionPending?"Subscription activation is pending. Do not pay again while confirmation is pending.":"Your reseller subscription is inactive. Subscribe or renew to verify a custom domain.");return}setBusy(true);try{await wickspendApi("wickspend/backend/reseller/domain/verify",{method:"POST",token,body:"{}"});const latest=await wickspendApi<any>("wickspend/backend/reseller/domain/status",{token});setDomain(latest);if(latest?.activation_ready)setMessage(`Connected — https://${latest.domain} is live with HTTPS.`);else setMessage("Domain detected. WickSpend is finishing routing and HTTPS automatically.")}catch(e){if(expectedDomainWait(e))setMessage("Not detected yet. Keep the CNAME in place — WickSpend is checking automatically.");else setMessage(err(e))}finally{setBusy(false)}}
 async function copyStoreLink(){if(!cleanStoreUrl)return;try{await navigator.clipboard.writeText(cleanStoreUrl);setMessage("Store link copied.")}catch{setMessage("Copy failed. Open the store and copy the URL manually.")}}
 async function shareStoreLink(){if(!cleanStoreUrl)return;try{if(navigator.share){await navigator.share({title:form.store_name||"My store",text:"Visit my store",url:cleanStoreUrl});setMessage("Store link shared.")}else await copyStoreLink()}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;setMessage("Could not share the store link.")}}

 if(loading)return <main className="resellerShell"><ResellerNav/><div className="resellerLoading">Loading store settings…</div></main>;
 const successMessage=["saved","created","checked","copied","shared","connected","detected","automatically","one dns"].some(word=>message.toLowerCase().includes(word));
 const domainLive=Boolean(domain?.activation_ready);
 const domainVerified=domain?.ownership_status==="verified";
 return <main className="resellerShell"><ResellerNav/><header className="resellerTopbar"><div><span className="eyebrow">Storefront</span><h1>Store & pricing</h1><p>Control your branding, launch state, selling rules and custom domain.</p></div><button className="secondaryButton" onClick={load}>Refresh</button></header>{!subscriptionActive&&<section className="resellerCard"><div className="cardHead"><div><span className="eyebrow">Read-only mode</span><h2>{subscriptionPending?"Activation pending":"Subscription inactive"}</h2><p className="subtle">{subscriptionPending?"Your store data is preserved while payment confirmation is pending. Do not pay again.":"Your store data is preserved. Subscribe or renew to change branding, pricing, rental settings or custom-domain configuration."}</p></div><a className="primaryButton compact" href="/reseller/billing">Manage Subscription</a></div></section>}{message&&<div className={`resellerMessage ${successMessage?"success":"error"}`}>{message}</div>}
 <section className="resellerGrid two"><article className="resellerCard formCard"><div className="cardHead"><div><span className="eyebrow">Branding</span><h2>Store settings</h2></div><span className={`status ${form.enabled?"good":"muted"}`}>{form.enabled?"Enabled":"Disabled"}</span></div><label>Store name<input disabled={!subscriptionActive} value={form.store_name} onChange={e=>setForm({...form,store_name:e.target.value})}/></label><label>Store slug<input disabled={!subscriptionActive} value={form.store_slug} onChange={e=>setForm({...form,store_slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]+/g,"-")})}/></label><label>Logo URL<input disabled={!subscriptionActive} value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})} placeholder="https://…"/></label><div className="formSplit"><label>Brand color<input disabled={!subscriptionActive} value={form.primary_color} onChange={e=>setForm({...form,primary_color:e.target.value})} placeholder="#0866F5"/></label><label>Support phone<input disabled={!subscriptionActive} value={form.support_phone} onChange={e=>setForm({...form,support_phone:e.target.value})}/></label></div><label>Support email<input disabled={!subscriptionActive} type="email" value={form.support_email} onChange={e=>setForm({...form,support_email:e.target.value})}/></label><label className="toggleLine"><input disabled={!subscriptionActive} type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span>Enable storefront</span></label><p className="subtle">Public purchases still require an active reseller subscription even if the storefront is enabled.</p><button className="primaryButton" disabled={busy||!subscriptionActive} onClick={saveStore}>{busy?"Saving…":"Save store settings"}</button>{cleanStoreUrl&&<div className="storeShareBox"><div><span>Clean store link</span><code>{cleanStoreUrl}</code></div><div className="storeShareActions"><a className="secondaryButton" href={cleanStoreUrl} target="_blank" rel="noreferrer">Open</a><button className="secondaryButton" type="button" onClick={copyStoreLink}>Copy</button><button className="primaryButton" type="button" onClick={shareStoreLink}>Share</button></div></div>}</article>
 <article className="resellerCard formCard"><div className="cardHead"><div><span className="eyebrow">Custom domain</span><h2>{domain?.domain||"Connect your domain"}</h2><p className="subtle">Use a subdomain like store.example.com. You only need one DNS record.</p></div><span className={`status ${domainLive?"good":domainVerified?"warn":"muted"}`}>{domainLive?"Connected":domainVerified?"Finishing setup":domain?.configured?"Waiting for DNS":"None"}</span></div><label>Domain<input disabled={!subscriptionActive||domainLive} value={domainInput} onChange={e=>setDomainInput(e.target.value)} placeholder="store.example.com"/></label>{!domainLive&&<button className="primaryButton" disabled={busy||!subscriptionActive||normalizeDomain(domainInput).length<4} onClick={requestDomain}>{busy?"Connecting…":domain?.configured?"Update domain":"Connect domain"}</button>}{domain?.configured&&<><dl className="detailList"><div><dt>DNS</dt><dd>{domainVerified?"Detected":"Waiting"}</dd></div><div><dt>Routing</dt><dd>{domain.routing_status||"pending"}</dd></div><div><dt>HTTPS</dt><dd>{domain.ssl_status||"pending"}</dd></div><div><dt>Status</dt><dd>{domainLive?"Live":"Automatic setup"}</dd></div></dl>{domain?.dns_verification&&!domainVerified&&<div className="dnsBox"><span>Record type</span><code>{domain.dns_verification.type||"CNAME"}</code><span>Name / host</span><code>{domain.dns_verification.name||domain.domain}</code><span>Points to</span><code>{domain.dns_verification.value||"wickspend.com"}</code></div>}{!domainLive&&!domainVerified&&<button className="secondaryButton" disabled={busy||!subscriptionActive} onClick={verifyDomain}>{busy?"Checking…":"I’ve added it — check now"}</button>}{domainLive&&<div className="storeShareBox"><div><span>Custom store URL</span><code>{`https://${domain.domain}`}</code></div><div className="storeShareActions"><a className="primaryButton" href={`https://${domain.domain}`} target="_blank" rel="noreferrer">Open store</a></div></div>}</>}<p className="subtle">After the CNAME is detected, WickSpend automatically handles VPS routing, HTTPS and final activation. No TXT record or manual support step needed.</p></article></section>
 <section className="resellerCard formCard"><div className="cardHead"><div><span className="eyebrow">Services</span><h2>Rent Number</h2><p className="subtle">Offer the existing WickSpend GotSMS rental catalog to your Mini Store customers.</p></div><span className={`status ${form.rent_number_enabled?"good":"muted"}`}>{form.rent_number_enabled?"Enabled":"Disabled"}</span></div><label className="toggleLine"><input disabled={!subscriptionActive} type="checkbox" checked={form.rent_number_enabled} onChange={e=>setForm({...form,rent_number_enabled:e.target.checked})}/><span>Enable Rent Number in this storefront</span></label><p className="subtle">Rental prices use the WickSpend wholesale floor plus your matching rental pricing rule. Disabling this hides the service and blocks new rental purchases server-side.</p><button className="primaryButton" disabled={busy||!subscriptionActive} onClick={saveStore}>{busy?"Saving…":"Save rental setting"}</button></section>
 <section className="resellerCard formCard"><div className="cardHead"><div><span className="eyebrow">Pricing</span><h2>Add or update a rule</h2></div><span className="status muted">{pricing.length} rules</span></div><div className="ruleGrid"><label>Product type<select disabled={!subscriptionActive} value={rule.product_type} onChange={e=>setRule({...rule,product_type:e.target.value})}><option value="number">Number</option><option value="rental">Rental</option><option value="marketplace">Marketplace</option><option value="boostly">Boostly</option></select></label><label>Product code<input disabled={!subscriptionActive} value={rule.product_code} onChange={e=>setRule({...rule,product_code:e.target.value})} placeholder="*"/></label><label>Country<input disabled={!subscriptionActive} value={rule.country_code} onChange={e=>setRule({...rule,country_code:e.target.value.toUpperCase()})} placeholder="US or blank"/></label><label>Markup ₦<input disabled={!subscriptionActive} type="number" min="0" value={rule.markup_ngn} onChange={e=>setRule({...rule,markup_ngn:e.target.value})}/></label><label>Fixed retail ₦<input disabled={!subscriptionActive} type="number" min="0" value={rule.fixed_price_ngn} onChange={e=>setRule({...rule,fixed_price_ngn:e.target.value})} placeholder="Optional"/></label><label className="toggleLine ruleToggle"><input disabled={!subscriptionActive} type="checkbox" checked={rule.enabled} onChange={e=>setRule({...rule,enabled:e.target.checked})}/><span>Enabled</span></label></div><p className="subtle">WickSpend’s wholesale price remains the hard floor. Rental rules use the GotSMS service code and optional country, just like existing pricing rules.</p><button className="primaryButton" disabled={busy||!subscriptionActive||!rule.product_code.trim()} onClick={saveRule}>Save pricing rule</button></section>
 <section className="resellerCard"><div className="cardHead"><div><span className="eyebrow">Current pricing</span><h2>Rules</h2></div></div>{pricing.length?<div className="tableWrap"><table><thead><tr><th>Type</th><th>Code</th><th>Country</th><th>Markup</th><th>Fixed price</th><th>State</th></tr></thead><tbody>{pricing.map((p:any,i:number)=><tr key={`${p.product_type}-${p.product_code}-${p.country_code}-${i}`}><td>{p.product_type}</td><td><b>{p.product_code}</b></td><td>{p.country_code||"All"}</td><td>₦{Number(p.markup_ngn||0).toLocaleString()}</td><td>{p.fixed_price_ngn==null?"—":`₦${Number(p.fixed_price_ngn).toLocaleString()}`}</td><td><span className={`status ${p.enabled?"good":"muted"}`}>{p.enabled?"Enabled":"Disabled"}</span></td></tr>)}</tbody></table></div>:<div className="emptyState">No pricing rules yet. Without a reseller rule, the WickSpend base price is used.</div>}</section>
 </main>
}
