"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import ResellerNav from "../ResellerNav";
import { ApiError, wickspendApi } from "@/lib/api";
import { getSessionToken } from "@/lib/session";

function err(error:unknown){return error instanceof ApiError ? (error.code || error.message) : error instanceof Error ? error.message : "Request failed."}
export default function ResellerStore(){
 const router=useRouter();
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[profile,setProfile]=useState<any>(null),[pricing,setPricing]=useState<any[]>([]),[domain,setDomain]=useState<any>(null);
 const[form,setForm]=useState({store_name:"",store_slug:"",logo_url:"",primary_color:"#0866F5",support_email:"",support_phone:"",custom_domain:"",enabled:false});
 const[rule,setRule]=useState({product_type:"number",product_code:"*",country_code:"",markup_ngn:"0",fixed_price_ngn:"",enabled:true});
 const[domainInput,setDomainInput]=useState("");
 const cleanStoreUrl=form.store_slug?`https://wickspend.com/store/${form.store_slug}`:"";
 const load=useCallback(async()=>{const token=getSessionToken();if(!token){router.replace("/login");return}setLoading(true);setMessage("");try{const[p,pr,d]=await Promise.all([wickspendApi<any>("wickspend/backend/reseller/profile",{token}),wickspendApi<any>("wickspend/backend/reseller/pricing",{token}),wickspendApi<any>("wickspend/backend/reseller/domain/status",{token})]);setProfile(p);setPricing(Array.isArray(pr?.items)?pr.items:[]);setDomain(d);const s=p?.store||{};setForm({store_name:s.store_name||"",store_slug:s.slug||"",logo_url:s.logo_url||"",primary_color:s.primary_color||"#0866F5",support_email:s.support_email||"",support_phone:s.support_phone||"",custom_domain:s.custom_domain||"",enabled:Boolean(s.enabled)});setDomainInput(d?.domain||s.custom_domain||"")}catch(e){setMessage(err(e))}finally{setLoading(false)}},[router]);
 useEffect(()=>{load()},[load]);
 async function saveStore(){const token=getSessionToken();if(!token)return;setBusy(true);setMessage("");try{await wickspendApi("wickspend/backend/reseller/store",{method:"POST",token,body:JSON.stringify(form)});setMessage("Store settings saved.");await load()}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function saveRule(){const token=getSessionToken();if(!token)return;setBusy(true);setMessage("");try{await wickspendApi("wickspend/backend/reseller/pricing",{method:"POST",token,body:JSON.stringify({...rule,markup_ngn:Number(rule.markup_ngn||0),fixed_price_ngn:rule.fixed_price_ngn===""?null:Number(rule.fixed_price_ngn)})});setMessage("Pricing rule saved.");await load()}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function requestDomain(){const token=getSessionToken();if(!token)return;setBusy(true);setMessage("");try{await wickspendApi("wickspend/backend/reseller/domain/request",{method:"POST",token,body:JSON.stringify({domain:domainInput.trim().toLowerCase()})});setMessage("Domain verification record created.");await load()}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function verifyDomain(){const token=getSessionToken();if(!token)return;setBusy(true);setMessage("");try{await wickspendApi("wickspend/backend/reseller/domain/verify",{method:"POST",token,body:"{}"});setMessage("DNS verification checked.");await load()}catch(e){setMessage(err(e))}finally{setBusy(false)}}
 async function copyStoreLink(){if(!cleanStoreUrl)return;try{await navigator.clipboard.writeText(cleanStoreUrl);setMessage("Store link copied.")}catch{setMessage("Copy failed. Open the store and copy the URL manually.")}}
 async function shareStoreLink(){if(!cleanStoreUrl)return;try{if(navigator.share){await navigator.share({title:form.store_name||"My store",text:"Visit my store",url:cleanStoreUrl});setMessage("Store link shared.")}else await copyStoreLink()}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;setMessage("Could not share the store link.")}}
 if(loading)return <main className="resellerShell"><ResellerNav/><div className="resellerLoading">Loading store settings…</div></main>;
 return <main className="resellerShell"><ResellerNav/><header className="resellerTopbar"><div><span className="eyebrow">Storefront</span><h1>Store & pricing</h1><p>Control your branding, launch state, selling rules and custom domain.</p></div><button className="secondaryButton" onClick={load}>Refresh</button></header>{message&&<div className={`resellerMessage ${message.toLowerCase().includes("saved")||message.toLowerCase().includes("created")||message.toLowerCase().includes("checked")||message.toLowerCase().includes("copied")||message.toLowerCase().includes("shared")?"success":"error"}`}>{message}</div>}
 <section className="resellerGrid two"><article className="resellerCard formCard"><div className="cardHead"><div><span className="eyebrow">Branding</span><h2>Store settings</h2></div><span className={`status ${form.enabled?"good":"muted"}`}>{form.enabled?"Enabled":"Disabled"}</span></div><label>Store name<input value={form.store_name} onChange={e=>setForm({...form,store_name:e.target.value})}/></label><label>Store slug<input value={form.store_slug} onChange={e=>setForm({...form,store_slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]+/g,"-")})}/></label><label>Logo URL<input value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})} placeholder="https://…"/></label><div className="formSplit"><label>Brand color<input value={form.primary_color} onChange={e=>setForm({...form,primary_color:e.target.value})} placeholder="#0866F5"/></label><label>Support phone<input value={form.support_phone} onChange={e=>setForm({...form,support_phone:e.target.value})}/></label></div><label>Support email<input type="email" value={form.support_email} onChange={e=>setForm({...form,support_email:e.target.value})}/></label><label className="toggleLine"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span>Enable storefront</span></label><p className="subtle">Public purchases still require an active reseller subscription even if the storefront is enabled.</p><button className="primaryButton" disabled={busy} onClick={saveStore}>{busy?"Saving…":"Save store settings"}</button>{cleanStoreUrl&&<div className="storeShareBox"><div><span>Clean store link</span><code>{cleanStoreUrl}</code></div><div className="storeShareActions"><a className="secondaryButton" href={cleanStoreUrl} target="_blank" rel="noreferrer">Open</a><button className="secondaryButton" type="button" onClick={copyStoreLink}>Copy</button><button className="primaryButton" type="button" onClick={shareStoreLink}>Share</button></div></div>}</article>
 <article className="resellerCard formCard"><div className="cardHead"><div><span className="eyebrow">Custom domain</span><h2>{domain?.domain||"Connect a domain"}</h2></div><span className={`status ${domain?.activation_ready?"good":domain?.ownership_status==="verified"?"warn":"muted"}`}>{domain?.domain_status||"none"}</span></div><label>Domain<input value={domainInput} onChange={e=>setDomainInput(e.target.value)} placeholder="store.example.com"/></label><button className="secondaryButton" disabled={busy||domainInput.trim().length<4} onClick={requestDomain}>Create verification record</button>{domain?.configured&&<><dl className="detailList"><div><dt>Ownership</dt><dd>{domain.ownership_status}</dd></div><div><dt>Routing</dt><dd>{domain.routing_status}</dd></div><div><dt>TLS</dt><dd>{domain.ssl_status}</dd></div><div><dt>Activation</dt><dd>{domain.activation_ready?"Live":"Not ready"}</dd></div></dl>{domain?.dns_verification&&<div className="dnsBox"><span>TXT record name</span><code>{domain.dns_verification.name}</code><span>TXT value</span><code>{domain.dns_verification.value}</code></div>}<button className="primaryButton" disabled={busy} onClick={verifyDomain}>Check DNS ownership</button></>}<p className="subtle">Ownership alone does not make a domain live. WickSpend also requires VPS routing, TLS and final activation.</p></article></section>
 <section className="resellerCard formCard"><div className="cardHead"><div><span className="eyebrow">Pricing</span><h2>Add or update a rule</h2></div><span className="status muted">{pricing.length} rules</span></div><div className="ruleGrid"><label>Product type<select value={rule.product_type} onChange={e=>setRule({...rule,product_type:e.target.value})}><option value="number">Number</option><option value="marketplace">Marketplace</option><option value="boostly">Boostly</option></select></label><label>Product code<input value={rule.product_code} onChange={e=>setRule({...rule,product_code:e.target.value})} placeholder="*"/></label><label>Country<input value={rule.country_code} onChange={e=>setRule({...rule,country_code:e.target.value.toUpperCase()})} placeholder="US or blank"/></label><label>Markup ₦<input type="number" min="0" value={rule.markup_ngn} onChange={e=>setRule({...rule,markup_ngn:e.target.value})}/></label><label>Fixed retail ₦<input type="number" min="0" value={rule.fixed_price_ngn} onChange={e=>setRule({...rule,fixed_price_ngn:e.target.value})} placeholder="Optional"/></label><label className="toggleLine ruleToggle"><input type="checkbox" checked={rule.enabled} onChange={e=>setRule({...rule,enabled:e.target.checked})}/><span>Enabled</span></label></div><p className="subtle">WickSpend’s wholesale price remains the hard floor. A fixed retail price below that floor is automatically raised to the floor.</p><button className="primaryButton" disabled={busy||!rule.product_code.trim()} onClick={saveRule}>Save pricing rule</button></section>
 <section className="resellerCard"><div className="cardHead"><div><span className="eyebrow">Current pricing</span><h2>Rules</h2></div></div>{pricing.length?<div className="tableWrap"><table><thead><tr><th>Type</th><th>Code</th><th>Country</th><th>Markup</th><th>Fixed price</th><th>State</th></tr></thead><tbody>{pricing.map((p:any,i:number)=><tr key={`${p.product_type}-${p.product_code}-${p.country_code}-${i}`}><td>{p.product_type}</td><td><b>{p.product_code}</b></td><td>{p.country_code||"All"}</td><td>₦{Number(p.markup_ngn||0).toLocaleString()}</td><td>{p.fixed_price_ngn==null?"—":`₦${Number(p.fixed_price_ngn).toLocaleString()}`}</td><td><span className={`status ${p.enabled?"good":"muted"}`}>{p.enabled?"Enabled":"Disabled"}</span></td></tr>)}</tbody></table></div>:<div className="emptyState">No pricing rules yet. Without a reseller rule, the WickSpend base price is used.</div>}</section>
 </main>
}
