"use client";

import {useMemo,useState} from "react";
import {BottomNav} from "@/components/BottomNav";
import styles from "./vpn-proxy.module.css";

type Plan={id:string;name:string;type:"VPN"|"Residential"|"Mobile";description:string;price:number;tag:string;location:string;session:string;duration:string;traffic:string};
const plans:Plan[]=[
{id:"usa-residential",name:"USA Residential Proxy",type:"Residential",description:"Dedicated • Rotating IP",price:4.9,tag:"MOST POPULAR",location:"United States",session:"Rotating",duration:"30 days",traffic:"Unlimited"},
{id:"uk-mobile",name:"UK Mobile Proxy",type:"Mobile",description:"4G / 5G • Private session",price:6.4,tag:"FAST",location:"United Kingdom",session:"Private",duration:"30 days",traffic:"Unlimited"},
{id:"germany-vpn",name:"Germany VPN",type:"VPN",description:"Unlimited traffic • 30 days",price:3.8,tag:"VALUE",location:"Germany",session:"Dedicated",duration:"30 days",traffic:"Unlimited"}
];
type View="browse"|"details"|"confirm"|"delivered";

export default function VpnProxy(){
 const[view,setView]=useState<View>("browse"),[active,setActive]=useState<Plan>(plans[0]),[tab,setTab]=useState("All"),[search,setSearch]=useState(""),[message,setMessage]=useState("");
 const filtered=useMemo(()=>plans.filter(p=>(tab==="All"||p.type===tab)&&`${p.name} ${p.location}`.toLowerCase().includes(search.toLowerCase())),[tab,search]);
 const select=(p:Plan)=>{setActive(p);setView("details");setMessage("")};
 const copy=async(v:string)=>{try{await navigator.clipboard.writeText(v);setMessage("Copied")}catch{setMessage("Copy unavailable")}};
 const credentials={host:"us.proxy.wickspend.net",port:"10482",username:"wick_840219",password:"8vQ2••••9L"};
 const goBack=()=>{setMessage("");setView(view==="confirm"?"details":"browse")};
 return <main className={styles.screen}>
  {view==="browse"&&<><header className={styles.top}><h1>VPN &amp; Proxy</h1><p>Private connections for safer account access.</p></header><input className={styles.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search country or plan"/><div className={styles.tabs}>{["All","VPN","Residential","Mobile"].map(t=><button type="button" key={t} onClick={()=>setTab(t)} className={`${styles.tab} ${tab===t?styles.active:""}`}>{t}</button>)}</div><h2 className={styles.sectionTitle}>Popular plans</h2><section className={styles.planList}>{filtered.map(p=><button type="button" className={styles.plan} key={p.id} onClick={()=>select(p)}><div><h3>{p.name}</h3><p>{p.description}</p></div><span className={styles.price}>${p.price.toFixed(2)}</span><span className={styles.tag}>{p.tag}</span><span className={styles.arrow}>›</span></button>)}</section><aside className={styles.info}><b>Use the right IP for your account</b><p>Choose a matching country to reduce login challenges.</p></aside></>}
  {view==="details"&&<><header className={styles.detailHeader}><button type="button" className={styles.back} onClick={goBack}>‹</button><div><h1>Plan details</h1><p>{active.name}</p></div></header><section className={styles.hero}><span className={styles.eyebrow}>{active.type.toUpperCase()}</span><h2>{active.name}</h2><p>{active.description}</p><div className={styles.heroPrice}><strong>${active.price.toFixed(2)}</strong><span>/ {active.duration}</span></div></section><h2 className={styles.specTitle}>What you get</h2><section className={styles.specs}><div className={styles.spec}><span>Location</span><b>{active.location}</b></div><div className={styles.spec}><span>IP type</span><b>{active.type}</b></div><div className={styles.spec}><span>Session</span><b>{active.session}</b></div><div className={styles.spec}><span>Traffic</span><b>{active.traffic}</b></div><div className={styles.spec}><span>Duration</span><b>{active.duration}</b></div></section><aside className={styles.note}><b>Best for account access</b><p>Use a location that matches the account region whenever possible.</p></aside><button type="button" className={styles.primary} onClick={()=>setView("confirm")}>Buy for ${active.price.toFixed(2)}</button><div className={styles.hint}>Paid from WickSpend Wallet</div></>}
  {view==="confirm"&&<><header className={styles.detailHeader}><button type="button" className={styles.back} onClick={goBack}>‹</button><div><h1>Confirm purchase</h1><p>Review before paying</p></div></header><section className={styles.confirmCard}><span className={styles.eyebrow}>VPN / PROXY</span><h2>{active.name}</h2><p>{active.description} • {active.duration}</p><div className={styles.confirmPrice}>${active.price.toFixed(2)} <small>one-time</small></div></section><section className={styles.summary}><h3>Order summary</h3><div className={styles.summaryRow}><span>Plan</span><b>{active.name}</b></div><div className={styles.summaryRow}><span>Duration</span><b>{active.duration}</b></div><div className={styles.summaryRow}><span>Subtotal</span><b>${active.price.toFixed(2)}</b></div><div className={styles.summaryRow}><span>Fees</span><b>$0.00</b></div><div className={styles.summaryRow}><span>Total</span><b>${active.price.toFixed(2)}</b></div></section><section className={styles.walletBox}><b>Pay with WickSpend Wallet</b><p>Wallet purchase will be enabled when the verified VPN/proxy order endpoint is connected.</p></section><button type="button" className={styles.primary} disabled onClick={()=>setView("delivered")}>Confirm &amp; pay ${active.price.toFixed(2)}</button><button type="button" className={styles.secondary} onClick={()=>setView("details")}>Cancel</button><p className={styles.message}>Purchase is currently unavailable. No wallet debit will occur.</p></>}
  {view==="delivered"&&<section className={styles.success}><div className={styles.successIcon}>✓</div><h1>Proxy ready</h1><p>Your access details are ready to use.</p><section className={styles.credentials}><h2>{active.name}</h2><p>Expires Oct 3, 2026</p>{Object.entries(credentials).map(([k,v])=><div className={styles.credential} key={k}><small>{k.toUpperCase()}</small><b>{v}</b><button className={styles.copy} type="button" onClick={()=>copy(v)}>Copy</button></div>)}<button type="button" className={styles.copyAll} onClick={()=>copy(Object.entries(credentials).map(([k,v])=>`${k}: ${v}`).join("\n"))}>Copy all details</button></section><aside className={styles.safe}><b>Keep these details private</b><p>Do not share proxy credentials. You can reopen them from Orders.</p></aside><button type="button" className={styles.primary} onClick={()=>location.assign("/orders")}>View in Orders</button><button type="button" className={styles.secondary} onClick={()=>setView("browse")}>Done</button>{message&&<p className={styles.message}>{message}</p>}</section>}
  <BottomNav/>
 </main>
}